### ISSUE TITLE
Running SuperDevmode fails in ClassNotFoundException: org.eclipse.jetty.server.nio.SelectChannelConnector

### ISSUE THREAD

**Issue by johndevs** [johndevs/gradle-vaadin-plugin#125]
The GWT Codeserver doesn't support Jetty 9 yet, so it will fail in 

```
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.nio.SelectChannelConnector
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
```

The GWT team are currently fixing it though, should be a non-issues as soon as Vaadin updates to a fixed version of GWT https://code.google.com/p/google-web-toolkit/issues/detail?id=8747

**Comment by zhuravskiy** [comment]
Same proplem also for :demo:vaadinDevMode with superDevMode false
