### ISSUE TITLE
CreateProcess error=206 on Windows for task "vaadinCompileWidgetset"

### ISSUE THREAD

**Issue by Alan47** [johndevs/gradle-vaadin-plugin#152]
Hi,
we are using your Gradle Plugin for our Vaadin project, and it serves us really well. However, there is one bug that keeps me from using it on my windows machine:

Execution failed for task ':com.example.webapp:vaadinCompileWidgetset'.
> java.io.IOException: Cannot run program "java": CreateProcess error=206, file name or extension is too long

Can you do something about this? You might want to look at this web link:
https://github.com/zhuravskiy/grails-vaadin-plugin/commit/e8cac1a2b952b668a3c2633290584596aaedf80e

... apparently somebody solved the problem for the Vaadin Grails Plugin.

It would be awesome if you could fix this.

**Comment by Alan47** [comment]
I temporarily managed to fix the issue by setting the environment variable
GRADLE_USER_HOME

... to something *really* short, like:
E:\guh

That seems to fix the issue, but I'm not sure if this is a permanent fix or if the issue will come back as I add more jars to the classpath...

**Comment by christoph-frick** [comment]
duplicate of #92?

**Comment by Alan47** [comment]
It might be. The underlying problem is the same, but the task that causes it is different. I'm not familiar enough with gradle to tell if its really the same issue...

**Comment by peterlitvak** [comment]
What is the right way to configure this?
If I only set the useClassPathJar property I get the following error:
```
Cannot get property 'mainAttributes' on null object
```

**Comment by Alan47** [comment]
Hey,
I'm still getting "CreateProcess error=206" from widget set and theme building on windows. I have vaadin.plugin.useClassPathJar set to 'true' in my 'build.gradle' file. Is there anything else I need to do to enable this?

**Comment by Davehuu** [comment]
Did you try Long Path Tool that also useful in situations where you see these error messages: Cannot read from source file or disk, there has been a sharing violation etc. i have used it. not yet get any problem.
