### ISSUE TITLE
Use gradle API to get java binaries

### ISSUE THREAD

**Issue by zeeke** [johndevs/gradle-vaadin-plugin#154]
Hi,

I get an error when using the plugin without the java executable in the PATH. I know this is not a very common pattern but in a distributed continuous integration system it is more robust to rely on the JAVA_HOME system property.

Actually, in UpdateAddonStylesTask.groovy at line 51, we should use some gradle API in order to get the right path of java binaries.

If needed, I can find time to tackle it.

**Comment by johndevs** [comment]
You are right, we should resolve the java executable better.

We cannot just rely on JAVA_HOME either as not everybody has that set either. Also Gradle provides ``org.gradle.java.home`` in *gradle.properties* which should also be prioritized if set.
