### ISSUE TITLE
Vaadin groovy plugin - Cannot change groovy version

### ISSUE THREAD

**Issue by dalibor983** [johndevs/gradle-vaadin-plugin#165]
In my project I use 'org.codehaus.groovy:groovy-all:2.4.1' as compile dependency but vaadin groovy plugin adds 'org.codehaus.groovy:groovy-all:2.3.4' in GroovyDependencyListener.afterEvaluate method and my built war has two groovy-all jars.

Is there any way to tell this plugin to use other groovy version than 2.3.4?

**Comment by dalibor983** [comment]
There is no two groovy-all jars. This plugin build groovy classes with version 2.3.4 but war contains 2.4.1 and I got this error:
```
groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.1 and you are trying to load version 2.3.4
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:509)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:77)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:71)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:53)
...
```

**Comment by johndevs** [comment]
Tried to reproduce the issue but cannot. Used the following setup:

build.gradle
```
dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.1'
}
```
The vaadin-groovy dependency is correctly upgraded (gradle dependencies says):
```
vaadin-groovy - Groovy library for vaadin projects
+--- org.codehaus.groovy:groovy-all:2.4.1
\--- org.codehaus.groovy:groovy-all:2.3.4 -> 2.4.1
```

And the project seems to be correctly be running using then vaadinRun task.

Could it be that you would have some old classes around from before you upgraded the dependency? You could try running the clean task and see if it helps.

**Comment by dalibor983** [comment]
@johndevs I changed vaadin groovy plugin from 0.9.2 to 0.9.7 and now everything working fine.
