### ISSUE TITLE
vaadin.gwt.jvmArgs does not work

### ISSUE THREAD

**Issue by cjalmeida** [johndevs/gradle-vaadin-plugin#169]
When you set the vaadin.gwt.jvmArgs configuration to any value, the widgetset compilation task produces an error.

The reason is that in GWTConfiguration.grooy, line 69, the value type is "String[]". Any list or string you assign to the variable is coerced into an array of strings instead of a list. So, in CompileWidgetsetTask.groovy, the "+=" operator does not work properly.

One solution to set the type of the variable to "def".

**Comment by johndevs** [comment]
Fixed in a8c52dfde665c4c90707ed3cb725c006ec6b3ab9
