### ISSUE TITLE
IDEA "compile" dependencies incorrectly created as "provided"

### ISSUE THREAD

**Issue by aparod** [johndevs/gradle-vaadin-plugin#171]
I'm using Gradle 2.3 and gradle-vaadin-plugin 0.9.7

My build script:

```
apply plugin: 'idea'
apply from: 'http://plugins.jasoft.fi/vaadin.plugin?version=0.9.7'

vaadin {
        version '7.4.3'
//      manageDependencies false
}

dependencies {
        compile 'org.apache.tika:tika-core:1.7'
}
```

Running the "idea" task results in the Tika dependency being marked as "provided" rather than "compile" in the .iml file.  Uncommenting `manageDependencies false` results in the dependency being correctly marked as "compile".

Apologies if I am missing something obvious here.

**Comment by aparod** [comment]
Looked into this a bit. Here's what I found:

* My compile dependency (Tika) is present in the compile configuration, as expected
* The Jetty9 configuration extends the runtime configuration, which extends the compile configuration
* The configureIdeaModule method adds the Jetty9 configuration to IDEA's "provided" scope, thereby marking everything in the __Jetty9, runtime, and compile configurations__ as belonging to the "provided" scope.

Modifying the Jetty9 configuration to not extend from anything seems to resolve the issue.  Submitting a pull request.

**Comment by johndevs** [comment]
Yes, looks like the Jetty configuration wouldn't need to extend the runtime configuration.
