### ISSUE TITLE
addons and missing resources

### ISSUE THREAD

**Issue by Ben1980** [johndevs/gradle-vaadin-plugin#172]
I still have to add the following dependencies:

compile group:'com.vaadin', name:'vaadin-cdi', version:'1.+'
compile group:'com.vaadin', name:'vaadin-client-compiled', version:'7.4.+'

Is there no way to handle this by the plugin automaticly?
is it possible to add addons through vaadinAddons or another method?
Wildfly is still complaining about missing valo resources, e.g. spinner.gif

**Comment by christoph-frick** [comment]
compiled gets added automatically if you don't use a widgetset

**Comment by johndevs** [comment]
As @christoph-frick says, the vaadin-client-compiled dependency is automatically added if you haven't set the ``vaadin.widgetset`` property. If you define a widgetset the client-compiler (and its dependencies) will get added instead so your widgetset gets automatically compiled.

The *vaadinAddons* task will only list addons from the directory, it will not add anything to your build files. Build files can contain so much custom logic that it would be unsafe for the plugin to start adding things into it. 

Not sure why Wildfly would complain about missing Valo resources. Might be related to GZip compression being enabled (as stated here http://stackoverflow.usinfonow.com/questions/27864923/vaadin-missing-icons-of-all-components). Anyway, I doubt it has something to do with the plugin.
