### ISSUE TITLE
Recompile in SuperDevMode not working with Vaadin 7.4.3

### ISSUE THREAD

**Issue by zhuravskiy** [johndevs/gradle-vaadin-plugin#176]
With Vaadin 7.4.3 i got
   [ERROR] Current binding properties are expanding to more than one permutation but per-file compilation requires that each compile operate on only one permutation.

settings for demo:
        gwt {
            draftCompile true
            userAgent "safari"
            collapsePermutations true
        }

**Comment by johndevs** [comment]
Are you running the SDM via a bookmarklet? 

I think support for using bookmarklets has been dropped since GWT 2.7.0 which Vaadin 7.4.x uses. 

http://stackoverflow.com/questions/27267704/gwt-super-dev-mode-recompile-doesnt-work

**Comment by zhuravskiy** [comment]
On 2.7.0 http://www.gwtproject.org/articles/superdevmode.html CodeServer  has argument [-[no]incremental], by default it switch on, if i set -noincremental, always works fine, i think SuperDevModeTask needs
something like this:

def superdevmodeProcess = ['java',
            '-cp', classpath.getAsPath(),
            'com.google.gwt.dev.codeserver.CodeServer',
            '-bindAddress', project.vaadin.devmode.bindAddress,
            '-port', 9876,
            '-workDir', widgetsetsDir.canonicalPath,
            '-src', javaDir.canonicalPath,
            '-logLevel', project.vaadin.gwt.logLevel,
            '-noprecompile',
            "-${project.vaadin.devmode.incremental? "" : "no"}incremental",
            project.vaadin.widgetset
        ]

About bookmarklet,  in the official documentation http://www.gwtproject.org/articles/superdevmode.html  says that bookmarklet still works and we must use it, on stackoverflow people can write anything.

**Comment by johndevs** [comment]
In the Google thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-web-toolkit-contributors/5lgtM77-1tM/rnNdb5UbDB8J that that stackoverflow post references Thomas Broyer who is one devs of GWT states that the bookmarklets will most likely never get fixed. I think the documentation over at gwtproject just hasn't been updated.

But you are right, we could add a way to add the *-noprecompile* option. I am thinking about adding a new parameter to ``vaadin.devmode.extraArgs``, similarly that has been done for the widgetset compiler, for adding any parameter for the CodeServer.

**Comment by zhuravskiy** [comment]
Thanks for understanding! Because without reloading, very hard to develop client part of addon.

**Comment by zhuravskiy** [comment]
Thanks!
