### ISSUE TITLE
plugin seems to cause weird dependency version for spring boot starter

### ISSUE THREAD

**Issue by eoliphan** [johndevs/gradle-vaadin-plugin#177]
Hi, i'm currently unable to use the plugin with the 1.0.0.beta2 version of the vaadin spring boot starter.  For some reason, when the plugin is 'applied' the 'com.vaadin:vaadin-spring-boot-starter:1.0.0.beta2' gets pushed to a com.vaadin:vaadin-spring-boot-starter:7.3.+ version, which of course doesn't exist.  I've tried forcing the dependency for 1.0.0.beta2 with both a custom resolution strategy as well as a 'force=true' on the dependency itself to no avail.    

I've poked around some in the plugin code, but it's really not clear what's causing the issue

**Comment by eoliphan** [comment]
Ok I think I've figured this out in DependencyListener.groovy

```
config.resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def group = details.requested.group
            def name = details.requested.name
            if(group == 'com.vaadin' && name.startsWith('vaadin-')) {
                if (!(name in blacklist) && !name.startsWith('vaadin-testbench')) {
                    details.useVersion project.vaadin.version
                }
            }
        }
```
The starter, etc meet that pattern but are not versioned along with the rest of a vaadin distro it looks like the starter just needs to be added to the blacklist

**Comment by christoph-frick** [comment]
is this the tipping point, where maybe a whitelist would be more appropriate? e.g. keep the few vaadin-something packages that we can guess the version from the config and rather keep the rest of them alone?
