### ISSUE TITLE
SuperDevMode on windows

### ISSUE THREAD

**Issue by zeeke** [johndevs/gradle-vaadin-plugin#179]
Hi,

I'm experiencing a problem with the plugin about running superDevMode on a windows machine.
I don't get any error in the console neither in log files but the code server doesn't serve any file.

here a relevant snippet of my configuration:

```
apply plugin: fi.jasoft.plugin.GradleVaadinPlugin

dependencies {
    providedCompile "com.vaadin:vaadin-client:7.4.1"
    providedCompile "com.vaadin:vaadin-server:7.4.1"
    providedCompile "javax.servlet:javax.servlet-api:3.0.1"
    compile "org.codehaus.jackson:jackson-core-asl:1.9.13"
    compile "org.codehaus.jackson:jackson-mapper-asl:1.9.13"
    
    testCompile "junit:junit:4.12"
    testCompile "org.mockito:mockito-all:1.9.5"
}

webAppDirName = 'WebContent'

sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = ['WebContent']
    }
    test {
        java.srcDirs = ['test']
    }
}

vaadin {
    manageWidgetset = false
    widgetset = '<path-to-widgetset>'
    addon.title = 'Addon Title'
    devmode.superDevMode=true
}

```

The task vaadinRun works well and on linux vaadinSuperDevMode works too.
Is there any other checks I can do?

**Comment by zhuravskiy** [comment]
widgetset = '<path-to-widgetset>' must be filled

**Comment by johndevs** [comment]
To get some better logging you could set ``vaadin.plugin.logToConsole = true`` and use the --info parameter when running the VDSM task.

**Comment by johndevs** [comment]
Did filling in the widgetset correctly solve the issue? Closing this for now until further information is added.
