### ISSUE TITLE
Additional Widgetset In Same WAR

### ISSUE THREAD

**Issue by dimitrichkhartishvili** [johndevs/gradle-vaadin-plugin#187]
I have two war projects (mobile and desktop) with different vaadin addons. 
how to configure vaadin gradle plugin to compile two widgetset? My idea is to merge two different war projects into single war project.

**Comment by johndevs** [comment]
What I would suggest is making the two projects into submodules and then set the widgetset property to different values.

Example (*build.gradle*):
```
subprojects {
    apply from: 'http://plugins.vaadin.com/vaadin.plugin'
}

project(':mobile'){ 
      vaadin {
           widgetset 'com.example.MobileWidgetset'
      }
}

project(':desktop'){
      vaadin {
           widgetset 'com.example.DesktopWidgetset'
      }
}
```
