### ISSUE TITLE
Classpath too long exception

### ISSUE THREAD

**Issue by jvmlet** [johndevs/gradle-vaadin-plugin#188]
Hello
I have issue with generateWidgetset task in project with very loooong  dependency list.
The task fails with "classpath too long" exception.
Would you please filter the jars in the class path to accept only those with Vaadin-Widgetsets attribute in MANIFEST.MF while building the classpath for com.google.gwt.dev.Compiler?
Thanks

**Comment by johndevs** [comment]
Limiting the classpath to only the jars with the Vaadin-Widgetsets attribute is  unfortunately not possible as many times you may want to use other GWT dependencies than Vaadin addons. 

Have you tried using the single jar classpath approach by setting ``vaadin.plugin.useClassPathJar = true``?

**Comment by christoph-frick** [comment]
@johndevs since this arises once in while: what are the downsides of `useClassPathJar`?  would it make a good default?

**Comment by jvmlet** [comment]
Yes, I tried to set useClassPathJar to true, but then the gwt Compiler fails with Illegal argument exception- it does't like some class from the dependency list

**Comment by christoph-frick** [comment]
@jvmlet can you track them down in the dependecies (configuration `vaadin-client`)?  if so you could exclude them for this configuration.

**Comment by jvmlet** [comment]
I ended up with 2 source sets
```
sourceSets {
    main {
        java {
            srcDirs = ['src/dummy/java']
        }
    }
    dummy {
        java {
            srcDirs = ['src/main/java']
        }
        compileClasspath += [project.configurations.providedCompile]
    }
}
dependencies {
dummyCompile(group: 'org.springframework', name: 'spring-webmvc', version: spring_version)
compile 'vaadin.addons.someAddon'
}
```
````dummy```` sour set substitutes  the main source and all java source dependencies go to ````dummyCompile```` configuration. As ```` compileWidgetset```` task grabs only main source set classpath - it sees only jars with vaadin addons.
Then I tweaked the compileJava and war tasks to compile and include dummy source set with dependencies to WEB-INF/classes.
Hope this helps others to overcome this issue.

**Comment by christoph-frick** [comment]
@jvmlet you can also just exclude just for the `vaadin-client`.  e.g. https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/build.gradle#L83-L91

**Comment by johndevs** [comment]
@christoph-frick The downsides/upsides of using the classpath jar approach is pretty nicely described [here](http://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html). The Maven Surefire plugin set it as a default a while ago and I think it would work for the Vaadin plugin as well. I think we could set it as default in the upcoming 0.10.0.

**Comment by johndevs** [comment]
Classpath jar is used as default on windows in 0.10
