### ISSUE TITLE
Gradle distzip VAADIN folder

### ISSUE THREAD

**Issue by acsadam0404** [johndevs/gradle-vaadin-plugin#189]
Gradle distZip task is a standard way to deploy libraries to production. It creates a lib folder containing the jar files and bin folder for startup scripts. 

Using this plugin, whats the correct path to place the VAADIN folder? Because the folder is large and I don't want to include it in the jar, it should be a standalone folder. The problem is the application can't find it.

**Comment by johndevs** [comment]
The VAADIN folder is usually placed in the *src/main/webapp* folder. It will then not be included in the jar but will be included in the WAR so the web application can find it.
