### ISSUE TITLE
vaadinRun-problem with CDI

### ISSUE THREAD

**Issue by thecrow69** [johndevs/gradle-vaadin-plugin#201]
I use the gradle-vaadin-plugin in an environment with Vaadin 7.5.5, vaadin-cdi 1.03, Weld 2.9.final and JEE 7.
When I start task vaadinRun the server throws the following error:
Exception in thread "main" java.lang.AbstractMethodError: javax.servlet.jsp.JspFactory.getJspApplicationContext(Ljavax/servlet/ServletContext;)Ljavax/servlet/jsp/JspApplicationContext;
at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:168)

I think this is based on the javax.servlet.jsp.JspFactory.getDefaultFactory()-implementation in javax:javaee-api:7.0 which searches for a class named org.apache.jasper.runtime.JspFactoryImpl as default. This class is found in the vaadin-client-compiler.jar but it has a version which doesn't implement the abstract method getJspApplicationContext(ServletContext context). 
But this method is called in the initialization of the WeldServletLifecycle. That is the reason of the exception.

What I don't understand is why the ApplicationServer-Task adds the compile-classpath to the runtime-classpath of the jetty. The vaadin-client-compiler is not needed as runtime-library but I found no possibility to exclude it from the jetty-classpath.

Hopefully you have any idea how to fix that.

Best,
Oliver

**Comment by johndevs** [comment]
Hi,

Would it be possible for you to either post a pre-configured build.gradle with your dependencies configured or alternatively a zipped project where this is failing? 

It would tremendously help in fixing the issue.

**Comment by johndevs** [comment]
CDI/EJB support will be added to ``0.11`` by replacing the default Jetty server with Payara in #72 . After that using CDI should work out-of-the-box with vaadinRun.
