### ISSUE TITLE
Exclude providedRuntime dependencies for WAR file task

### ISSUE THREAD

**Issue by moberwasserlechner** [johndevs/gradle-vaadin-plugin#204]
Hi,

in #186 you added the runtime dependencies to the war file but its also needed to remove the dependencies in the "providedRuntime" configuration to have a proper war file.

It should work by adding following lines to "fi/jasoft/plugin/TaskListener.groovy"

```groovy
// Remove providedRuntime dependencies
war.classpath -= project.configurations.providedRuntime
```

Thanks

**Comment by johndevs** [comment]
Indeed it should! Thanks.
