### ISSUE TITLE
Expose Gretty config options

### ISSUE THREAD

**Issue by CSBaum** [johndevs/gradle-vaadin-plugin#207]
First of all, thanks for all the hard work you have put into this plugin, it's amazing!

I have an enhancement request, not really an issue, would it be possible to expose some of the Gretty configuration options?  For instance, if we could use a flag to switch between jetty & tomcat that would be great.

Thanks!

Sean

**Comment by johndevs** [comment]
Hi,

The plugin doesn't internally use Gretty, it only embeds a Jetty server. 

The next minor release ``0.11`` will support multiple servers, namely Payara (http://www.payara.fish) for 
EJB/CDI support and Jetty as a more lightweight server. You will be able to switch between the servers using the configuration option ``vaadin.server = 'jetty'/'payara'``. 

There is currently no plans for Tomcat support, at least yet,  but it could be added in the future if needed.
