### ISSUE TITLE
Disable Jar Generation?

### ISSUE THREAD

**Issue by pluttrell** [johndevs/gradle-vaadin-plugin#212]
Is there a way to disable the automatic generation of the following JARs?
```
{project.name}-{project.version}-javadoc.jar
{project.name}-{project.version}-sources.jar
```

**Comment by johndevs** [comment]
You could try adding the following to your build.gradle:
```
configurations.archives.artifacts.with { archives ->
    archives.removeAll {
        it.classifier in ['javadoc', 'sources']
    }
}
```

**Comment by johndevs** [comment]
Closing this as this is already a year old. Re-open if this still an issue even with the solution above.
