### ISSUE TITLE
Disabling Javadoc failOnError Doesn't Work

### ISSUE THREAD

**Issue by pluttrell** [johndevs/gradle-vaadin-plugin#213]
We have a project deployed as an EAR file that contains a common (core) library and multiple WARs. For example sake, here's a description of the project structure:

```
/project-root
    /core
    /web1   
    /web2
```

Since the `core.jar` is shared both both web projects, it's deployed in the `/lib` dir in the EAR (along with other shared dependencies). Continuing our example, here's the deployment layout:

```
project.ear
    /lib
        /core.jar
    /web1.war
    /web2.war
```

Classes in the `/core` are required for all the web projects, so in `/project-root/web1/build.gradle` we declare a dependency as such:

```
dependencies {
    providedCompile project(':core')
}
```

This has worked great for some time. 

But now we're trying to add a third war (`/web3`) that uses Vaadin and the gradle-vaadin-plugin and our `/web3` builds fail because there are javadoc errors in `/core`. How do we disable failing the build on javadoc errors? This is normally controlled by setting the following property, but this isn't working for us with the gradle-vaadin-plugin plugin:

```
javadoc.failOnError = false
```

I also wonder why `/web3` is running _javadoc_ on a separate sub-project.

**Comment by johndevs** [comment]
Sorry, can't seem to reproduce this with the current plugin. 
Can you try again with the latest plugin and re-open if the issue is still present?
