### ISSUE TITLE
Push parameter not recognised when Vaadin loaded through 3rd party

### ISSUE THREAD

**Issue by davidsowerby** [johndevs/gradle-vaadin-plugin#217]
I am building  an application using krail, which in turns builds on Vaadin (7.5.10 in this case), and version 0.10.4 of your plugin.

This all works fine until I try and add Vaadin Push (which is not included in the krail jar)

The first configuration below does not work and produces a "Push not available" error, the second works (by explicitly declaring a dependency on vaadin-push).  This latter fine as a workaround, but does require declaring the version of an indirect dependency.

The other option is to always include push in the krail jar, but I would rather have the choice of whether or not to do that.

As I have 2 possible workarounds, this is clearly not urgent - and thanks for the plugin, it saves me a lot of time.

-----------
Config 1 (fails)

```groovy
dependencies {
    compile 'uk.q3c.krail:krail:0.9.7'
    compile 'uk.q3c.krail:krail-jpa:0.9.1'
}

vaadin {
    widgetset 'com.example.tutorial.widgetset.tutorialWidgetset'
    plugin.logToConsole = true
    push true
}
```
Config 2 (works)

```
dependencies {
    compile 'uk.q3c.krail:krail:0.9.7'
    compile 'uk.q3c.krail:krail-jpa:0.9.1'
    compile 'com.vaadin:vaadin-push:' + '7.5.10'
}

vaadin {
    widgetset 'com.example.tutorial.widgetset.tutorialWidgetset'
    plugin.logToConsole = true
}
```
The error with Config 1:

> Dec 27, 2015 5:02:00 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.IllegalStateException: Push is not available. See previous log messages for more information.
	at com.vaadin.ui.PushConfigurationImpl.setPushMode(PushConfiguration.java:184)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:204)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)

**Comment by johndevs** [comment]
Hi,

Hmm, the first config and the second one is working  fine for me, I get with both setups:
```
INFO: Atmosphere is using async support: org.atmosphere.container.Jetty9AsyncSupportWithWebSocket running under container: jetty/9.3.0.v20150612 with WebSocket enabled.
Jan 27, 2016 7:32:43 PM org.atmosphere.cpr.AtmosphereFramework info
INFO: Atmosphere Framework 2.2.7.vaadin1 started.
Jan 27, 2016 7:32:43 PM org.atmosphere.cpr.AtmosphereFramework interceptor
INFO: Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT
```
when running with **vaadinRun**. This indicates that push is working as intended.

If you are not running with **vaadinRun** then you need to ensure that your external server gets the **vaadin-push** configuration on its classpath.

**Comment by davidsowerby** [comment]
Sorry it took so long to respond - I missed your update somehow.

Thanks for taking the time to check this.  It seems a bit strange that one config worked and not the other, but as it appears not to be related to this plugin, I'll close the issue
