### ISSUE TITLE
File separator back slashes (Windows) are invalid in Widgetset stylesheet paths

### ISSUE THREAD

**Issue by moberwasserlechner** [johndevs/gradle-vaadin-plugin#218]
Hi,

My OS is Windows and therefore File.separator results in a backslash.

When I tried to let the plugin manage my Widgetset by setting
```
vaadin.manageWidgetset = true
```
it generated backslashes in the resulting Widgetset.gwt.xml. In the web application the backslashes are removed and the css file is not found or loaded.

The UpdateWidgetsetTask searching for css and scss files to write them as stylesheet elements. The resulting file paths contains backslashes. 
```
        // Retrive CSS files
        File[] clientCSS = TemplateUtil.getFilesFromPublicFolder(project, CSS_FILE_POSTFIX)
        clientCSS.each {

            // Get the relative path to the public folder
            def path = it.parent.substring(it.parent.lastIndexOf(PUBLIC_FOLDER) + PUBLIC_FOLDER.length())
            if (path.startsWith(File.separator)) {
                path = path.substring(1);
            }

            def scssFile = it.name
            stylesheets.add(path ? path + File.separator + scssFile : scssFile)
        }
```

I must be ensured that all back slashes are replaced with forward slashes as soon as the path is written to `<stylesheet src="path_without_backslashes">` in the xml file.

BR,
Michael

**Comment by johndevs** [comment]
Hi,

I think this issues is the same as #198? 

That fix was released in 0.10.2. What version of the plugin are you using?

**Comment by moberwasserlechner** [comment]
I'm using 0.10.4 with Gradle 2.10
```
------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Windows 7 6.1 amd64
```

Issue #198 had a leading back slash but my problem is the back slash within the path
```
<stylesheet src="fi_jasoft_dragdroplayouts\dragdroplayouts.css" />
```

**Comment by johndevs** [comment]
I see, thanks @moberwasserlechner for the clarification.
