### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by yissachar** [johndevs/gradle-vaadin-plugin#219]
When using the plugin I get the following deprecation warning:

> The plus(Iterable<FileCollection>) method and using the '+' operator in conjunction with an Iterable<FileCollection> object have been deprecated and are scheduled to be removed in 3.0.  Please use the plus(FileCollection) method or the '+' operator with a FileCollection object instead.

**Comment by christoph-frick** [comment]
duplicate of #209

**Comment by yissachar** [comment]
Oops, didn't see that, thanks. I'll wait for 0.10.5 to be released.
