### ISSUE TITLE
addShutdownHook and Gradle Daemon Issue

### ISSUE THREAD

**Issue by zeeke** [johndevs/gradle-vaadin-plugin#220]
Hi,

I experienced a performance problem using this plugin in a large project with the Gradle Daemon enabled.

I found that the use of addShutdownHook let the JVM keep a reference to some plugin tasks, that in turn keep references to the gradle world. This causes memory problem with a few build.

Let me know if I shoul make a PR.

**Comment by johndevs** [comment]
Assumed Groovy would cleanup automatically any hooks added by addShutDownHook since there doesn't exist a removeShutDownHook. But apparently it does not.  

Thanks for reporting this!
