### ISSUE TITLE
vaadinUpdateWidgetset : "String index out of range: 1"

### ISSUE THREAD

**Issue by canthony** [johndevs/gradle-vaadin-plugin#227]
I am getting a "String out of range:1" error when updating my widgetset with 0.10.5 of the plugin.

This error does not occur with 0.10.4

Attached : build.gradle, and logs from 0.10.4 and 0.10.5

[build.gradle.txt](https://github.com/johndevs/gradle-vaadin-plugin/files/104571/build.gradle.txt)
[v0.10.4.log.txt](https://github.com/johndevs/gradle-vaadin-plugin/files/104569/v0.10.4.log.txt)
[v0.10.5.log.txt](https://github.com/johndevs/gradle-vaadin-plugin/files/104570/v0.10.5.log.txt)

**Comment by johndevs** [comment]
Hi,

This should have already been fixed in 0fda3c1d32055abc791ed10807970432b2049264 along with #225. Should be fixed in the next maintenance release 0.10.6.
