### ISSUE TITLE
Missing attribute Vaadin-Package-Version in Addon-Zip

### ISSUE THREAD

**Issue by moberwasserlechner** [johndevs/gradle-vaadin-plugin#228]
Hi,

the task 'vaadinAddonZip' creates a manifest which misses 
```
'Vaadin-Package-Version': '1',
```

This causes the Upload to the Vaadin directory to fail with:

![image](https://cloud.githubusercontent.com/assets/1049938/12695205/7ad8a602-c746-11e5-8307-55cacf0902df.png)

Responsible method is `gradle-vaadin-plugin/src/main/groovy/fi/jasoft/plugin/TaskListener.groovy#configureAddonZipMetadata`.

Thanks,
Michael

**Comment by johndevs** [comment]
@moberwasserlechner Could you make a pull request with that commit?

**Comment by moberwasserlechner** [comment]
Sorry I totally forget about the change. I created the PR.

**Comment by johndevs** [comment]
Thanks for the PR!
