### ISSUE TITLE
vaadinCompileThemes does not include .scss definitions from addon components into addons.scss

### ISSUE THREAD

**Issue by maksym72** [johndevs/gradle-vaadin-plugin#232]
When compiling Vaadin themes, addons.scss is overriden with empty mixin definition, without having to include style information from included addons:

@mixin addons {
}

**Comment by johndevs** [comment]
Are  you sure you have the addons with the styles on your compile classpath and the addons MANIFEST.MF exposes the scss styles?

The plugin will go through the compile classpath and populate the addons mixin if the addons have correct support.

**Comment by maksym72** [comment]
Yes, I'm pretty shure.

In compile dependencies I have 

compile (
...
group: 'org.vaadin.addons', name: 'contextmenu', version: '4.5'
)

and the manifest of context menu addon contains the following:

Manifest-Version: 1.0
Vaadin-Stylesheets: VAADIN/themes/contextmenu/contextmenu.scss
Implementation-Title: ContextMenu
Implementation-Version: 4.5
Vaadin-Widgetsets: org.vaadin.peter.contextmenu.ContextmenuWidgetset
Vaadin-Package-Version: 1
Class-Path:

**Comment by maksym72** [comment]
John,

since this issue is blockinng for our project, I'm wondering, when 0.10.7 will be released? 

Thank you a lot for investing your time into this amazing plugin.

**Comment by johndevs** [comment]
@maksym72 ``0.10.7`` was just released today :smile:

**Comment by maksym72** [comment]
Great, already tried it and now addons.scss is looking good. :)
