### ISSUE TITLE
How do I set the logging level to DEBUG?

### ISSUE THREAD

**Issue by tuscland** [johndevs/gradle-vaadin-plugin#238]
Hello,

I am not sure if this is a question about the gradle-vaadin-plugin, but this might be the best place to ask it since I am using the plugin.

I have searched a way to change the logging level, but I am confused at all the levels (no pun intended!) of indirection.  In my Groovy code, I use the `@Slf4j` annotation to enable a logger on my class.

So what is the correct way to enable debug messages to the console.

Thanks!
Cam

PS: I have set the `vaadin.plugin.logToConsole` property to `true`.

**Comment by johndevs** [comment]
Try adding the parameter ``--debug`` when you run Gradle. That should turn on debug logging to console.

**Comment by tuscland** [comment]
Hi John,
Thanks for the info. There is now debugging output but the amount of logging is just overwhelming. Is there a way to control exactly what gets logged? Adding logging.properties or jetty-logging.properties does not help.

**Comment by johndevs** [comment]
There are many ways you can control the log level of Gradle. The plugin just utilizes the existing Gradle logger to log its output.

Have a look at https://docs.gradle.org/current/userguide/logging.html.  Example 22.4 and Section 22.4 might be the most interesting to you as they allow you to control what log level is output to the console.

Closing this issue as it is not directly related to the plugin, but more about how logging is done with Gradle in general.
