### ISSUE TITLE
Compiling widgetset with addon located in the same source base as project

### ISSUE THREAD

**Issue by maksym72** [johndevs/gradle-vaadin-plugin#240]
Hello!
Are there any possibility to point plugin in any way to scan project source path in addition to dependencies in a build file? We just want to avoid a separation of 2 classes to a deicated addon/library.

**Comment by johndevs** [comment]
What do you mean by "Scan the classpath"?

If you put your addon client side classes of your addon in the *client* package of the project and add a widgetset to your project then the addons will be available in your project without  packaging them in as addons. Is this what you meant?

**Comment by maksym72** [comment]
Exactly.

**Comment by johndevs** [comment]
@maksym72 

The newly released ``0.11.4`` should improve this. If you split out the addon/library into its own module and add a dependency to that module then the plugin will now find the widgetset.

For an example you could have a look at the new wiki article about building addons at https://github.com/johndevs/gradle-vaadin-plugin/wiki/Building-addons and if you need an example you can run the **vaadinCreateAddonProject** task that will create a project that has an addon and a demo project that depends on that addon.
