### ISSUE TITLE
how to compile widgetset with vaadin 7.6.3 with gradle

### ISSUE THREAD

**Issue by rphadake** [johndevs/gradle-vaadin-plugin#243]
Hi,

I have a sample vaadin project and trying to create donut chart using pie chart as custom widget.
Added this in build.gradle :  apply from: 'http://plugins.jasoft.fi/vaadin.plugin'
Added @Widgetset("com.example.dashboard") to UI class and have a corresponding .gwt.xml file.

Doing "gradle vaadinCompile" fails for :vaadin:vaadinUpdateWidgetSet.  This doesn't show any error.
Using Gradle Vaadin Plugin 0.11.0-beta2 here.

Thanks,
Ram

**Comment by christoph-frick** [comment]
does `build/logs/widgetset-compile.log` provide any clues?

**Comment by johndevs** [comment]
You can also try to run with *--info*. It might provide you with more detailed information.

**Comment by rphadake** [comment]
There is no build/logs folder generated, am I missing any obvious setting?

**Comment by johndevs** [comment]
You will need to post some more information for us to be able to help you. 

Could you post the console output when you run ```gradle --info vaadinUpdateWidgetSet```? Also posting your **build.gradle** might help in determining the cause.

**Comment by rphadake** [comment]
This started working after doing following changes:
classpath(group: 'fi.jasoft.plugin', name: 'gradle-vaadin-plugin', version: '0.11.0-beta5')   (in dependencies)
apply plugin: 'fi.jasoft.plugin.vaadin'

Thanks.
