### ISSUE TITLE
Spring Boot and Vaadin Widgetsets

### ISSUE THREAD

**Issue by trisbez** [johndevs/gradle-vaadin-plugin#244]
Hello-

  We are attempting to use the gradle vaadin plugin(v 0.10.7) with Spring Boot (v 1.3.2.RELEASE) and gradle version 2.12.We have a multi-module setup, but I've attached a simple example that, hopefully, illustrates the issue we are seeing.  When I do a **gradle vaadinCompileWidgetset** I do not see any widgetsets generated and when I do a **gradle bootrun** and access http://localhost:8080 it is not able to find any widgetsets.

  I'm sure I must be missing something simple here, but any help would be appreciated.

Thanks!

[demo7.zip](https://github.com/johndevs/gradle-vaadin-plugin/files/270508/demo7.zip)

**Comment by johndevs** [comment]
Hi,

There were a couple of things that needed to get fixed to get it to work. 
* I upgraded the Vaadin Gradle plugin to 0.11.0-beta4 which will autodetect your widgetset. If you want to stay with the 0.10.x series then you need to add ``vaadin.widgetset='AppWidgetset'` to your build.gradle
* I upgraded the Vaadin version used in the project to be a more recent one (the build was pulling in 7.4.x which is really old)

Here is the revised **build.gradle** that should work. Just run ``gradle vaadinCompile bootrun`` and it should work.

```
buildscript {
        ext {
                springBootVersion = '1.3.2.RELEASE'
        }
        repositories.jcenter()
        dependencies {
                classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        }
}

plugins {
    id "fi.jasoft.plugin.vaadin" version "0.11.0-beta4"
}

apply plugin: 'java'
apply plugin: 'eclipse-wtp'
apply plugin: 'spring-boot'

jar {
        baseName = 'demo7'
        version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
        compile('com.vaadin:vaadin-spring-boot-starter:1.0.0')
        compile('org.vaadin.addons:aceeditor:0.8.14')
        testCompile('org.springframework.boot:spring-boot-starter-test')
}

eclipse {
        classpath {
                 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
                 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
        }
}

vaadin {
       // Use latest vaadin 7.6 series
        version '7.6.+'
}
```

**Comment by trisbez** [comment]
Thank you for the quick reply!  I'm trying to move that change back into my main project and I've run into a new issue.  In this project I have 3 modules where the dependencies look like 
   **codeGeneration <- services <- vaadin**

In the codeGeneration project we are creating java code from XSDs. After applying the changes you provided and running **gradle build** I receive the following error 

* What went wrong:
Execution failed for task ':demo7:vaadinUpdateAddonStyles'.
> java.io.FileNotFoundException: C:\data\source\generated-code\build\generated-sources\cxf (Access is denied)

I assume that the gradle plugin is scanning the full classpath for any items.  Is there a way to exclude all other modules from the scan, or based off of the directory structure (exclude=\*\*generated\*\*)?

  Thanks once again!

**Comment by johndevs** [comment]
Yes, the task uses the compile classpath (``project.sourceSets.main.compileClasspath``) of the project. I'm not sure your build will work correctly if there are files on that classpath which are not accessable by the filesystem. Maybe check the file permissions of those files?

**Comment by trisbez** [comment]
Thanks again for that!  I'll see what I can get or create a new project that reproduces this and open a new issue
