### ISSUE TITLE
0.11.0-beta4 downloads beta2

### ISSUE THREAD

**Issue by CSBaum** [johndevs/gradle-vaadin-plugin#245]
When I updated the version of the gradle-vaadin-plugin to v0.11.0-beta4 it downloaded the beta4 as expected, but it then downloaded the beta2 version while resolving classpath dependencies.  

Thanks for all the hard work you are putting into this plugin, it's really a time/life saver! 

Sean

**Comment by johndevs** [comment]
Thanks for noticing this! Actually it downloads the correct version, but the version number in that build artifact is internally not correct. It is a problem with the plugin release build itself.
