### ISSUE TITLE
Compiling WidgetSet in Windows while having com.vaadin.tapio:googlemaps:1.2.1 addon fails

### ISSUE THREAD

**Issue by klaussemarsse** [johndevs/gradle-vaadin-plugin#247]
I am using the gradle-vaadin-plugin to build my vaadin application which uses the com.vaadin.tapio:googlemaps:1.2.1 addon. My gradle build file is as follow:

> apply plugin: "java"
> apply plugin: "war"
> apply from: "http://plugins.jasoft.fi/vaadin.plugin?version=0.11-SNAPSHOT"
> repositories {
>     jcenter()
>     maven{
>         url "http://maven.vaadin.com/vaadin-addons"
>     }
> }
> vaadin.plugin.logToConsole = true
> //vaadin.plugin.useClassPathJar = true
> vaadin{
>     widgetset "us.icitap.cc.ui.AppWidgetset"
> }
> dependencies {
>     compile "org.slf4j:slf4j-api:1.7.21"
>     testCompile "junit:junit:4.12"
>     //compile group: 'com.vaadin', name: 'vaadin-client-compiled', version: '7.6.6'
>     providedCompile group: "javax.servlet", name: "javax.servlet-api", version: "3.1.0"
>     compile group: "com.vaadin", name: "vaadin-cdi", version: "1.0.3"
>     compile "com.vaadin.tapio:googlemaps:1.2.1"
> }

Trying to execute task vaadinCompile on my Windows PC did not succeed and the problem was the googlemaps addon. The widgetset compilation was unable to recognize the dependent libraries of googlemaps even though they were imported and included correctly into the project classpath. The error was as follow:

> Errors in 'jar:file:/C:/Users/KLAU/.gradle/caches/modules-2/files-2.1/com.vaadin.tapio/googlemaps/1.2.1/3504f75674a0e59ace0350ddbfe602dca2b0de53/googlemaps-1.2.1.jar!/com/vaadin/tapio/googlemaps/client/GoogleMapInitListener.java'
> Line 12: No source code is available for type com.google.gwt.maps.client.MapWidget; did you forget to inherit a required module?
> Tracing compile failure path for type 'com.vaadin.tapio.googlemaps.client.GoogleMapWidget'
> Errors in 'jar:file:/C:/Users/KLAU/.gradle/caches/modules-2/files-2.1/com.vaadin.tapio/googlemaps/1.2.1/3504f75674a0e59ace0350ddbfe602dca2b0de53/googlemaps-1.2.1.jar!/com/vaadin/tapio/googlemaps/client/GoogleMapWidget.java'
> Line 105: No source code is available for type com.google.gwt.maps.client.events.center.CenterChangeMapHandler; did you forget to inherit a required module?
> Line 321: No source code is available for type com.google.gwt.maps.client.events.dragend.DragEndMapHandler; did you forget to inherit a required module?
> Line 70: No source code is available for type com.google.gwt.maps.client.layers.KmlLayer; did you forget to inherit a required module?
> Line 508: No source code is available for type com.google.gwt.maps.client.overlays.PolylineOptions; did you forget to inherit a required module?
> .....................................

But what was strange is that the same project, same configuration could compile successfully  on my Ubuntu laptop having the same Java JDK: ( jdk1.8.0_92) on both my windows and ubuntu

After two full days of trying, searching and testing I was able to identify the problem by noticing that when I call the task vaadinCompile on ubuntu the dependent task :vaadinClassPathJar got SKIPPED, while on windows it got executed and created a project-name-classpath.jar

After adding the line:

> vaadin.plugin.useClassPathJar = false

on my build.gradle on Windows I finally got the widgetset compiled

I spent a lot of time searching for the solution and the information I could found was very modest so I hope this post will help somebody having the same problems

**Comment by christoph-frick** [comment]
this behaviour was introduced in #188

**Comment by johndevs** [comment]
When using the classpath jar (default on Windows) the widgetset compiler will only include the dependencies on its classpath that a) are vaadin client dependencies or b) dependencies which jar manifest contains the 'Vaadin-Widgetset' property indicating it is an addon that should be included in the widgetset. 

This is to ensure that no conflicting third-party dependencies are pulled into the client compilers classpath.

**Comment by johndevs** [comment]
Documented this restriction and work-around in https://github.com/johndevs/gradle-vaadin-plugin/wiki/Using-addons
