### ISSUE TITLE
0.11.0-beta4 launches Tomcat vs. Jetty

### ISSUE THREAD

**Issue by CSBaum** [johndevs/gradle-vaadin-plugin#248]
Normally, i am ambivalent to which app server is launched with vaadinRun, but it seems that when Tomcat launches, it does not completely recreate the directory structure that a 'normal' tomcat instance would have and that is problematic since my vaadin app is looking for a configuration file in the --> 'webapps/myApp/WEB-INF' directory, but in the instance that got launched i found --> 'applications/myApp/WEB-INF' directory.

Do you override the default web app location when launching tomcat? Is there a configuration setting that lets us set the value in gradle?

Thanks in advance,

Sean

**Comment by johndevs** [comment]
The Vaadin plugin does not come with Tomcat, it only comes with Payara and Jetty where Payara is the default when running vaadinRun. Please check to see that you aren't using some other plugin that uses tomcat to run the project with.

**Comment by CSBaum** [comment]
Sorry, that was my bad, i naturally assumed that the other choice besides jetty would be tomcat.  Is there a flag in the 0.11 versions to select which server to run? Along those lines, since it looks like you expanded the option of app servers, what would it take to include Tomcat in the list of app servers to launch?

**Comment by johndevs** [comment]
You can select the server by adding ``vaadinRun.server = 'jetty' or 'payara'``

To include a new server a couple of classes needs to written for the plugin that tells the plugin how to run the server and what dependencies it requires. Currently that cannot be done outside of the plugin, but must be included in the plugin.

**Comment by CSBaum** [comment]
Thanks, the vaadinRun.server did the trick and thanks for the plugin info, if i have time later next week i will see if i can take a stab at adding Tomcat support if you think it's beneficial.
