### ISSUE TITLE
Canot build with 0.11.0-beta5

### ISSUE THREAD

**Issue by piercer** [johndevs/gradle-vaadin-plugin#249]
Hi,

I have had a project working with this plugin using version 0.10.6 for a long time. I only use it to build my vaadin project, never to run it.

I am trying to upgrade to 0.11.0-beta5, but no matter what I do it always fails with

```
:vaadinUpdateWidgetset FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinUpdateWidgetset'.
> Configuration with name 'vaadin-server' not found.

```

My only vaadin config is

```
vaadin {
    version 7.6.6
    manageRepositories false
    manageDependencies false
    push true
}
```

I have no idea how to fix this, please advise

**Comment by johndevs** [comment]
Currently the plugin expects that there exists a ``vaadin-server`` configuration in the build which contains the vaadin server side libraries. If you disable the dependency management with ``mangeDependencies = false`` then you have to create the configuration yourself.
