### ISSUE TITLE
Apply plugin on submodule

### ISSUE THREAD

**Issue by trisbez** [johndevs/gradle-vaadin-plugin#250]
Hello

I have a project with a number of sub-modules that do not require vaadin and one that does. Something along these lines 
-mainModule
  - childMoule2
  - childMoule2
  - ...
  - vaadin

Is there a way to limit the scope of the compile to the "vaadin" module? 

my build.gradle has the following 
```javascript
buildscript {
    ext { springBootVersion = '1.3.2.RELEASE' }
    repositories {
        mavenLocal()
        maven { url "${artifactory_contextUrl}" + "/repo" }
    }
    dependencies {
        classpath('io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE')
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath(group: 'fi.jasoft.plugin', name: 'gradle-vaadin-plugin', version: '0.11.0-beta5')
    }
}
apply plugin: 'fi.jasoft.plugin.vaadin'
...
project(':vaadin') {

    dependencies {
        compile project(':childModule1')
        compile('org.vaadin.addons:aceeditor:0.8.14')
    }
    bootRepackage {
        enabled = false
    }
    vaadin {
        widgetset "com.test.AppWidgetset"
        manageRepositories false
        manageDependencies false
    }
}
```

I did try to apply the plugin directly in the module but my build began to fail saying that it could resolve third 3rd party artifacts although they are on our Artifactory instance.

` 
  > Could not resolve com.github.rutledgepaulv:rest-query-engine:0.6.3.
  > Could not get resource 'http://dl.bintray.com/johndevs/maven/com/github/rutledgepaulv/rest-query-engine/0.6.3/rest-query-engine-0.6.3.pom'.
  > Could not GET 'http://dl.bintray.com/johndevs/maven/com/github/rutledgepaulv/rest-query-engine/0.6.3/rest-query-engine-0.6.3.pom'.
  > Connect to dl.bintray.com:80 [dl.bintray.com/75.126.118.188, dl.bintray.com/108.168.243.150] failed: Connection refused: connect`

Thanks much!

**Comment by johndevs** [comment]
Have you defined your artifactory repositories for the sub-modules? Defining the repository inside the ``buildScript`` closure only makes the repository available for the build script resolution, not for the build itself.

**Comment by trisbez** [comment]
I had initially found that I could override it in the vaadin configuration something like 
```
project(':vaadin') {
    apply plugin: 'fi.jasoft.plugin.vaadin'

    bootRepackage {
        enabled = false
    }
    vaadin {
        plugin {
            repositories.maven { repository ->
                repository.name = 'Bintray.com Maven repository'
                repository.url = "${artifactory_contextUrl}" + "/repo"
            }
        }
        gwt{
            outputDirectory file('build/classes/main/')
        }
        manageWidgetset false
        manageRepositories false
    }
}```
but that was obviously foolish... Thanks for the clarification!
