### ISSUE TITLE
Starting application from jar-file (java -jar ....)

### ISSUE THREAD

**Issue by thomaspp** [johndevs/gradle-vaadin-plugin#253]
Hello all,

I have an additional question. With gradle task bootRepackage it is possible to create a jar-file with all included libs. 

The first thing what I'm wondering is why starting in Eclipse Jetty is used and with the jar-file a Tomcat server? 

An additional error will be shown by starting the page in the browser: Failed to load the widgetset: ./../VAADIN/widgetsets/customizedWidgetset/customizedWidgetset.nocache.js?1464332079362

Do you have any idea how I will get run the application...?

Best Regards,
Thomas

**Comment by thomaspp** [comment]
Hello again,

Now I found out how I can start the application:

java -Dspring.profiles.active=dev -jar **test.war**

But is this really the way how to start the application?

Best Regards,
Thomas

**Comment by christoph-frick** [comment]
> The first thing what I'm wondering is why starting in Eclipse Jetty is used and with the jar-file a Tomcat server? 

Tomcat is the default in springboot. See the springboot docs for how to change that (iirc undertow and jetty are supported out of the box)

> An additional error will be shown by starting the page in the browser: Failed to load the widgetset: ./../VAADIN/widgetsets/customizedWidgetset/customizedWidgetset.nocache.js?1464332079362

Assuming, your widgetset is built properly, then have you made sure, that compiling the widgetset is part of packing for the fatjar?  e.g.: https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/gradle/springboot-vaadin-fixes.gradle#L21-L29

**Comment by christoph-frick** [comment]
> But is this really the way how to start the application?

Yes, once the war plugin gets into your springboot setup, you will end up with a fat jar as a .war file (which can be used now "everywhere").  This plugin pulls in war. If the "fix" to this problem is make the transitive use of `war` in this plugin optional or disable this behaviour in the springboot I have never investigated.

**Comment by thomaspp** [comment]
Wow... Thanks for the fast answer!

But why eclipse use jetty (I have no special configuration -> default) and with the command line tomcat is used?

**Comment by christoph-frick** [comment]
> But why eclipse use jetty (I have no special configuration -> default) and with the command line tomcat is used?

I don't use eclipse, so i don't _know_ what's going on.  But this plugin comes funpacked with features run/develop vaadin only with this plugin (no springboot/container/... needed).  Maybe you are starting the e.g. `vaadinRun` task instead of `bootRun`?

**Comment by thomaspp** [comment]
Okay, currently I start the application in Eclipse with lunch files instead of gradle tasks. Is it possible to start the application with vaadinRun and system parameter (-Dspring.profiles.active=dev)?

**Comment by christoph-frick** [comment]
My guess here is, that you don't want to run vaadinRun, since i doubt it will pick up on your springboot relevant configs.  Either run the bootRun gradle task or start your Application.main() for springboot behaviour.

**Comment by thomaspp** [comment]
Okay, last question... ;-)

and bootRun with -D parameter?

**Comment by christoph-frick** [comment]
I use this to pass down props: https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/gradle/springboot-vaadin-fixes.gradle#L32

**Comment by thomaspp** [comment]
Perfect, thanks for your help!
