### ISSUE TITLE
Problem with building custom component connector, using gradle-vaadin-plugin

### ISSUE THREAD

**Issue by holydos** [johndevs/gradle-vaadin-plugin#258]
Hi
I tried to build custom component with connector using gradle-vaadin-plugin.
My component is extended vaadin Tree, with extended vaadin TreeConnector.
Compilation was successfull, but in application my custom component still connected with basic connector.
After that i tried to create simple appication, try to compile and build my custom component whith maven. And my component was compiled and connected correctly. 

What could be the problem?

**Here is my custom component source code**

@Connect(MainTree.class)
public class MainTreeConnector extends TreeConnector {

    @Override
    protected Widget createWidget() {
        return GWT.create(VTree.class);
    }
    @Override
    protected void init() {
        this.getWidget().connector = this;
    }

    public VTree getWidget() {
        return (VTree)super.getWidget();
    }

    @Override
    public void updateFromUIDL(UIDL uidl, ApplicationConnection client) {
        if (!AbstractComponentConnector.isRealUpdate(uidl)) {
            return;
        }

        getWidget().rendering = true;

        getWidget().client = client;

        if (uidl.hasAttribute("partialUpdate")) {
            handleUpdate(uidl);

            // IE8 needs a hack to measure the tree again after update
            WidgetUtil.forceIE8Redraw(getWidget().getElement());

            getWidget().rendering = false;
            return;
        }

        getWidget().paintableId = uidl.getId();

        getWidget().immediate = getState().immediate;

        getWidget().disabled = !isEnabled();
        getWidget().readonly = isReadOnly();

        getWidget().dragMode = uidl.hasAttribute("dragMode") ? uidl
                .getIntAttribute("dragMode") : 0;

        getWidget().isNullSelectionAllowed = uidl
                .getBooleanAttribute("nullselect");
        getWidget().isHtmlContentAllowed = uidl
                .getBooleanAttribute(TreeConstants.ATTRIBUTE_HTML_ALLOWED);

        if (uidl.hasAttribute("alb")) {
            getWidget().bodyActionKeys = uidl.getStringArrayAttribute("alb");
        }

        getWidget().body.clear();
        // clear out any references to nodes that no longer are attached
        getWidget().clearNodeToKeyMap();
        tooltipMap.clear();

        VTree.TreeNode childTree = null;
        UIDL childUidl = null;
        for (final Iterator<?> i = uidl.getChildIterator(); i.hasNext();) {
            childUidl = (UIDL) i.next();
            if ("actions".equals(childUidl.getTag())) {
                updateActionMap(childUidl);
                continue;
            } else if ("-ac".equals(childUidl.getTag())) {
                getWidget().updateDropHandler(childUidl);
                continue;
            }
            childTree = getWidget().new TreeNode();
            getConnection().getVTooltip().connectHandlersToWidget(childTree);
            updateNodeFromUIDL(childTree, childUidl, 1);
            getWidget().body.add(childTree);
            childTree.addStyleDependentName("root");
            childTree.childNodeContainer.addStyleDependentName("root");
        }
        if (childTree != null && childUidl != null) {
            boolean leaf = !childUidl.getTag().equals("node");
            childTree.addStyleDependentName(leaf ? "leaf-last" : "last");
            childTree.childNodeContainer.addStyleDependentName("last");
        }
        final String selectMode = uidl.getStringAttribute("selectmode");
        getWidget().selectable = !"none".equals(selectMode);
        getWidget().isMultiselect = "multi".equals(selectMode);

        if (getWidget().isMultiselect) {
            Roles.getTreeRole().setAriaMultiselectableProperty(
                    getWidget().getElement(), true);

            if (BrowserInfo.get().isTouchDevice()) {
                // Always use the simple mode for touch devices that do not have
                // shift/ctrl keys (#8595)
                getWidget().multiSelectMode = MultiSelectMode.SIMPLE;
            } else {
                getWidget().multiSelectMode = MultiSelectMode.valueOf(uidl
                        .getStringAttribute("multiselectmode"));
            }
        } else {
            Roles.getTreeRole().setAriaMultiselectableProperty(
                    getWidget().getElement(), false);
        }

        getWidget().selectedIds = uidl.getStringArrayVariableAsSet("selected");

        // Update lastSelection and focusedNode to point to *actual* nodes again
        // after the old ones have been cleared from the body. This fixes focus
        // and keyboard navigation issues as described in #7057 and other
        // tickets.
        if (getWidget().lastSelection != null) {
            getWidget().lastSelection = getWidget().getNodeByKey(
                    getWidget().lastSelection.key);
        }

        if (getWidget().focusedNode != null) {

            Set<String> selectedIds = getWidget().selectedIds;

            // If the focused node is not between the selected nodes, we need to
            // refresh the focused node to prevent an undesired scroll. #12618.
            if (!selectedIds.isEmpty()
                    && !selectedIds.contains(getWidget().focusedNode.key)) {
                String keySelectedId = selectedIds.iterator().next();

            }
        }

        if (getWidget().lastSelection == null
                && getWidget().focusedNode == null
                && !getWidget().selectedIds.isEmpty()) {
            getWidget().setFocusedNode(
                    getWidget().getNodeByKey(
                            getWidget().selectedIds.iterator().next()));
            getWidget().focusedNode.setFocused(false);
        }

        // IE8 needs a hack to measure the tree again after update
        WidgetUtil.forceIE8Redraw(getWidget().getElement());

        getWidget().rendering = false;

    }
    private void updateActionMap(UIDL uidl) {
        final Iterator<?> it = uidl.getChildIterator();
        while (it.hasNext()) {
            final UIDL action = (UIDL) it.next();
            final String key = action.getStringAttribute("key");
            final String caption = action
                    .getStringAttribute(TreeConstants.ATTRIBUTE_ACTION_CAPTION);
            String iconUrl = null;
            if (action.hasAttribute(TreeConstants.ATTRIBUTE_ACTION_ICON)) {
                iconUrl = getConnection()
                        .translateVaadinUri(
                                action.getStringAttribute(TreeConstants.ATTRIBUTE_ACTION_ICON));
            }
            getWidget().registerAction(key, caption, iconUrl);
        }

    }
    private void handleUpdate(UIDL uidl) {
        final VTree.TreeNode rootNode = getWidget().getNodeByKey(
                uidl.getStringAttribute("rootKey"));
        if (rootNode != null) {
            if (!rootNode.getState()) {
                // expanding node happened server side
                rootNode.setState(true, false);
            }
            String levelPropertyString = Roles.getTreeitemRole()
                    .getAriaLevelProperty(rootNode.getElement());
            int levelProperty;
            try {
                levelProperty = Integer.valueOf(levelPropertyString);
            } catch (NumberFormatException e) {
                levelProperty = 1;
                VConsole.error(e);
            }

            renderChildNodes(rootNode, (Iterator) uidl.getChildIterator(),
                    levelProperty + 1);
        }
    }

    void renderChildNodes(VTree.TreeNode containerNode, Iterator<UIDL> i, int level) {
        containerNode.childNodeContainer.clear();
        containerNode.childNodeContainer.setVisible(true);
        while (i.hasNext()) {
            final UIDL childUidl = i.next();
            // actions are in bit weird place, don't mix them with children,
            // but current node's actions
            if ("actions".equals(childUidl.getTag())) {
                updateActionMap(childUidl);
                continue;
            }
            final VTree.TreeNode childTree = getWidget().new TreeNode();
            getConnection().getVTooltip().connectHandlersToWidget(childTree);
            updateNodeFromUIDL(childTree, childUidl, level);
            containerNode.childNodeContainer.add(childTree);
            if (!i.hasNext()) {
                childTree
                        .addStyleDependentName(childTree.isLeaf() ? "leaf-last"
                                : "last");
                childTree.childNodeContainer.addStyleDependentName("last");
            }
        }
        containerNode.childrenLoaded = true;
    }

}

public class MainTree extends Tree {

    private NodeStyleSupplier nodeStyleSupplier;

    public MainTree() {
    }

    public NodeStyleSupplier getNodeStyleSupplier() {
        return this.nodeStyleSupplier;
    }

    public void setNodeStyleSupplier(NodeStyleSupplier nodeStyleSupplier) {
        this.nodeStyleSupplier = nodeStyleSupplier;
    }

    public Transferable getTransferable(Map<String, Object> payload) {
        if(this.nodeStyleSupplier == null) {
            return super.getTransferable(payload);
        } else {
            TreeTransferable transferable = new TreeTransferable(this, this, payload);
            Object object = payload.get("itemId");
            if(object != null) {
                Object value = this.itemIdMapper.get((String)object);
                transferable.setData("itemId", value);
                String nodeStyle = (String)this.nodeStyleSupplier.apply(value);
                if(StringUtils.isNotEmpty(nodeStyle)) {
                    transferable.setData(nodeStyle, Boolean.valueOf(true));
                }
            }

            return transferable;
        }
    }
}

**And gradle build**
plugins {
    id "fi.jasoft.plugin.vaadin" version "0.10.7"
}

group 'ua.com.smartway'
version '1.0-SNAPSHOT'

apply plugin: 'java'
//apply plugin: 'war'
//apply from: 'http://plugins.jasoft.fi/vaadin.plugin'

task explodedWar(type: Copy) {
    into "../out/ui-exploded"
    with war
}

repositories {
    maven {
            url "http://maven.vaadin.com/vaadin-addons"
    }
}

vaadin {

    /**
     * Defines what version of Vaadin the plugin should use. The version can be
     * defined as a specific number (7.1.13) or as a string where '+' means the latest.
     *
     * This version is used by the plugin to automatically add the right Vaadin dependencies
     * to the project.
     *
     * The default is the latest version of Vaadin 7.
     */
    version '7.6.4'
    push false
    widgetset 'TitanWidgetSet'

    manageWidgetset true
    plugin.themesDirectory 'build/resources/main/VAADIN/themes'
    gwt.outputDirectory file('build/resources/main')
}

dependencies {
    compile project(':titan.api')

    compile (
        [group:'com.vaadin', name:'vaadin-server', version: vaadin.version],
        [group:'com.vaadin', name:'vaadin-client', version: vaadin.version],
        [group:'com.vaadin', name:'vaadin-client-compiled', version: vaadin.version],
        [group:'com.vaadin', name:'vaadin-client', version: vaadin.version],
        [group:'com.vaadin', name:'vaadin-push', version: vaadin.version],
        [group:'com.vaadin', name:'vaadin-themes', version: vaadin.version],
        [group:'org.vaadin.addon', name:'confirmdialog', version:'2.1.3'],
        [group: 'com.vaadin.addon', name: 'vaadin-context-menu', version: '0.7.3'],
        [group: 'org.vaadin.addons', name: 'formcheckbox', version: '1.0.2'],
        commonLibraries.logging,
        commonLibraries.ideaAnnotations
    )

    compile 'org.springframework:spring-core:' + springVersion
    compile 'org.springframework:spring-web:' + springVersion
    compile 'org.springframework:spring-webmvc:' + springVersion
    compile 'org.springframework:spring-jdbc:' + springVersion
    compile 'org.springframework:spring-context:' + springVersion
    /*compile 'org.springframework:spring-instrument:' + springVersion*/
    compile 'org.springframework:spring-tx:' + springVersion
    compile 'org.springframework:spring-aspects:' + springVersion
    compile 'org.springframework:spring-test:' + springVersion
    compile 'com.fasterxml.jackson.core:jackson-core:2.6.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.6.3'
    compile 'com.vaadin:vaadin-spring:1.0.0'
    compile 'org.vaadin:resetbuttonfortextfield:1.2.1'
    compile 'org.vaadin.artur:KeyActions:0.1.1'

    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'commons-beanutils:commons-beanutils:1.9.2'
    compile(commonLibraries.commonsCollections)

    testCompile 'org.eclipse.jetty:jetty-server:9.3.6.v20151106'
    testCompile 'org.eclipse.jetty:jetty-servlet:9.3.6.v20151106'
    //testCompile 'org.eclipse.jetty.websocket:websocket-server:9.3.6.v20151106'
    testCompile 'org.seleniumhq.selenium:selenium-java:2.53.0'
    testCompile 'com.jayway.awaitility:awaitility:1.7.0'
    testCompile 'org.eclipse.jetty.websocket:javax-websocket-server-impl:9.3.6.v20151106'
    testCompile 'javax.websocket:javax.websocket-api:1.0'
    testCompile 'org.codehaus.janino:janino:2.7.8'
    testCompile commonLibraries.awaitility
    testCompile 'org.mockito:mockito-core:1.10.19'

    providedCompile 'javax.servlet:javax.servlet-api:3.1.0'

    compile files('libs/contains-css-style-client-side-criterion-1.0.jar')
    compile files('libs/tree.jar')
}

task titanCompileWidgetsetThemes {
    description = 'compile Titan widgetset and themes'

    dependsOnOrdered(titanCompileWidgetsetThemes,
            vaadinUpdateWidgetset,
            vaadinCompileThemes,
            vaadinCompileWidgetset
    )
}

task testTitan {
    description = 'configure and run UI tests for Titan'
    group = 'verification'

    dependsOnOrdered(testTitan, clean, titanCompileWidgetsetThemes, test)
}

void dependsOnOrdered(Task task, Task... others) {
    task.dependsOn(others)
    for (int i = 0; i < others.size() - 1; i++) {
        others[i + 1].mustRunAfter(others[i])
    }
}

**Comment by johndevs** [comment]
Have you annotated your UI class with ``@Widgetset("TitanWidgetSet")``?
