### ISSUE TITLE
vaadinRun possible classloader issue

### ISSUE THREAD

**Issue by fortiernor** [johndevs/gradle-vaadin-plugin#259]
I am trying to use vaadinRun with jetty to deploy my application, but when I try to access the application I get an error which indicates that my embedded db4o database does not "see" my application classes. (This particular application runs correctly with tomcat when I point the application context's docBase to my exploded war directory.) Running vaadinRun with debug indicates that jetty is started with the correct "classesDir" argument.

As the error happens in one of the application classes, these are obviously being executed by Jetty. My research seems to indicate that this would be a classloader issue, but I am not versed in webapp classloader issues.
Would you have any suggestion as to what might be wrong?
Thank you!
[debug_jetty.txt](https://github.com/johndevs/gradle-vaadin-plugin/files/305458/debug_jetty.txt)

**Comment by johndevs** [comment]
You most likely do not have libncurses installed on your system. 

For more information have a look at https://discuss.gradle.org/t/how-do-i-always-force-console-auto-in-a-gradle-properties-or-environment-variable/12039/5.

This is not really a plugin issue, but more of a Gradle issue so closing this.
