### ISSUE TITLE
vaadin.plugin.eclipseOutputDir Parameter works in IDEA breaking the build

### ISSUE THREAD

**Issue by moberwasserlechner** [johndevs/gradle-vaadin-plugin#260]
Hi,

I have a build file with both "eclipse" and "idea" plugins enabled and and die IDEA Gradle plugin installed.

```
plugins {
  id 'fi.jasoft.plugin.vaadin' version '0.11'
}
apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'eclipse'
apply plugin: 'idea'

vaadin {
  widgetset = "MyWidgetset"
  vaadin.version = "${vaadinVersion}"
  vaadin.debug = false
  vaadin.manageWidgetset = true
  vaadin.plugin.logToConsole = true
  vaadin.plugin.eclipseOutputDir = "bin/"
  vaadin.gwt.gwtSdkFirstInClasspath = true
}
```

>  vaadin.plugin.eclipseOutputDir = "bin/"

1. Refresh the gradle project using IDEA Gradle plugin
2. Make the project
3. "/bin/" directory appears in addition to the "build"

![image](https://cloud.githubusercontent.com/assets/1049938/16038879/56f7b0f6-3227-11e6-8f02-3d0c7507add6.png)
4. Make the project again 
5. You might experience problems with tests because the main module classes are not found anymore.

Remove either the eclipse plugin or the "eclipseOutputDir" property solves the problem.

I think as "eclipseOutputDir" is a Eclipse specific parameter it should be ignored in any other IDE.

Thanks,
Michael

**Comment by johndevs** [comment]
Unfortunatly Gradle itself doesn't know where or by who it is run. The IDE's just run gradle as it would be run from the command line.

The way the plugin can differentiate between where it is run is to check if the idea or the eclipse plugins are applied. But in your case you are applying both saying that the project is run in both IDE's which means the plugin thinks you are running in both and applies both eclipse and intellij settings which can conflict.

What you can do is add a property to your build stating in which IDE the user is running and apply the idea or eclipse plugin accordingly. It is up to the developer to then run the build with that parameter.
