### ISSUE TITLE
0.11 does not pickup idea IDE config block anymore

### ISSUE THREAD

**Issue by moberwasserlechner** [johndevs/gradle-vaadin-plugin#261]
After upgrade to 0.11 from 0.10.7 the following configuration block does not work anymore.

```
idea {
    module {
        inheritOutputDirs = true
    }
}
```

If I switch back to 0.10.7 it works again.

I use:
```
IntelliJ IDEA 2016.1.3
Build #IU-145.1617, built on June 3, 2016
JRE: 1.8.0_60-b27 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
```

*0.10.7*
![image](https://cloud.githubusercontent.com/assets/1049938/16223061/d1404fde-379b-11e6-95ea-bb4306d82137.png)
results in
![image](https://cloud.githubusercontent.com/assets/1049938/16223111/106db6f6-379c-11e6-8fa5-e0ba1e9a4e5c.png)

*0.11*
Now I do the same in 0.11 by just changing the version.
![image](https://cloud.githubusercontent.com/assets/1049938/16223153/41b9bfde-379c-11e6-8baa-8f6f8ca46262.png)
results in 
![image](https://cloud.githubusercontent.com/assets/1049938/16223178/5267a36e-379c-11e6-8e62-0bfa31afa547.png)

I tested this with a very simple project. https://github.com/moberwasserlechner/idea-gradle-tester

Thanks,
Michael

**Comment by johndevs** [comment]
Alright, thanks for reporting this! 

Should be fixed now.
