### ISSUE TITLE
How can I use the plugin offline?

### ISSUE THREAD

**Issue by fortiernor** [johndevs/gradle-vaadin-plugin#262]
I need to have a Vaadin project on a laptop cannot access a remote repository. I copied all the required jars in a local directory, declared as "flatDir", but when I try to build I get the following error:
    A problem occurred configuring root project '[...]'.
    > Could not resolve all dependencies for configuration ':vaadin-run-server'.
       > Could not download jetty-annotations.jar (org.eclipse.jetty:jetty-annotations:9.3.6.v20151106)
          > Could not get resource 'https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-annotations/9.3.6.v20151106/jetty-annotations-9.3.6.v20151106.jar'.
             > Could not HEAD 'https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-annotations/9.3.6.v20151106/jetty-annotations-9.3.6.v20151106.jar'.
                > Connect to repo1.maven.org:443 [repo1.maven.org/151.101.44.209] failed: Connection refused: connect

Yet I copied the jetty-annotations jar in the local "flatDir" and declared it as a dependency:
    compile "org.eclipse.jetty:jetty-annotations:9.3.6.v20151106"

This is how I am applying the gradle-vaadin-plugin:
    buildscript {
    	repositories {
    		flatDir {
    			dirs 'c:/local/lib'
                }
        }
        dependencies {
        	classpath 'fi.jasoft.plugin:gradle-vaadin-plugin:0.11'
        }
    }
    apply plugin: 'fi.jasoft.plugin.vaadin'

**Comment by CSBaum** [comment]
Have you tried running gradle in offline mode?

./gradlew vR --offline

This will make gradle read it's caches and assuming that you are 'connected' at least once before you run gradle with the offline flag, the plugin should be there ....

Sean

**Comment by fortiernor** [comment]
Thank you, but that's precisely the assumption I cannot make. Thanks to this post:
[https://discuss.gradle.org/t/want-to-use-local-dependencies-because-i-have-no-internet-access-noob-desperate/4739/2]
I seem to be able to get everything working, except the vaadin-gradle plugin. And since the gradle cache is not portable:
[https://issues.gradle.org/browse/GRADLE-2690]
... no luck.

**Comment by johndevs** [comment]
I don't think the plugin can do much when it comes to offline support. It relies on Gradle to resolve the correct dependencies and if Gradle is unable to find the dependencies from your local Maven/Gradle cache then you need to have a look on why those dependencies are not in your cache.
