### ISSUE TITLE
output.resourcesDir should be in the application server classpath 

### ISSUE THREAD

**Issue by michaz** [johndevs/gradle-vaadin-plugin#263]
for vaadinRun, along with output.classesDir.

Otherwise, classpath resources are never found by the application server, except if one uses a (I think) non-standard configuration, where resources are also written to classesDir.

I tried this, and it works for me (with Jetty):

https://github.com/michaz/gradle-vaadin-plugin/commit/6481b93c1637c18698717e781a1d0d0c9044186f

This seems to conflict with the special case for Eclipse, though, see comment, and I'm not sure what to do about that.

**Comment by johndevs** [comment]
Setting ``vaadinRun.classesDir`` does not alter you build in any way, it will just point the server to that directory for everything needed to run the webapp. It is up to the developer to get all the necessary compiled classes and resources into that directory if needed. Consider that directory as a expanded WAR archive.

There are two use-cases for this:

**1) I want to compile my Gradle project into a War but I wan to also test it in Eclipse with vaadinRun. I don't want to mix classes compiled by Eclipse with classes compiled by Gradle.**

In this case you want to set vaadinRun.classesDir to ``bin`` as that is where Eclipse puts both class and resource files, but you still want Gradle to put the classes and resources into build/classes as that is what gets added to the WAR.

**2) I want to compile all my classes into another directory than the standard one and run it with vaadinRun**

In this case you want to point both eclipse and Gradle to the same directory, you can do that by 
```
   sourceSets {
                main.output.classesDir = 'bin'
                main.output.resourcesDir = 'bin'
            }
    vaadinRun {
            classesDir 'bin'
    }
```

**3) I want to compile all my classes to the standard Gradle classes dir, even from Eclipse**

In this case you want to set ``project.eclipse.classpath.defaultOutputDir = project.sourceSets.main.output.classesDir`` so eclipse configures the project to compile the classes to the standard Gradle classes location. 

--

I am guessing you want 2) but haven't pointed the resource dir to the custom classes dir?

I added a warning about when you no classes can be found in the custom classesDir which most likely indicate that you haven't pointed either Gradle or Eclipse to the right location.

**Comment by michaz** [comment]
Thanks! My remark about Eclipse was confusing, I think (I don't use it). It's rather:

4.) I want to compile all my classes to the standard Gradle classes dir, and I want to have Gradle copy all my resources to the standard Gradle resources dir, and I want vaadinRun to pick up both classes and resources from these dirs.

Currently, only classes are picked up, not resources, becuase only the classes dir is passed to the app server.

**Comment by johndevs** [comment]
Hi, thanks for clarifying the issue. 

The resource directory should now be by default added if you haven't set the vaadinRun.classesDir. If you do set it, then you have to manually add both classes and resources to that directory by yourself.
