### ISSUE TITLE
Server doesn't start on version 0.11.1

### ISSUE THREAD

**Issue by yissachar** [johndevs/gradle-vaadin-plugin#264]
I've been using version 0.9.8 of the plugin. I tried updating to version 0.11.1 but encountered [this issue](https://github.com/johndevs/gradle-vaadin-plugin/issues/247). Adding `plugin.useClassPathJar = false` as described there fixed it so that I don't get any errors, but the server never starts. It manages all the steps up to compiling the theme, but after compiling the theme it just hangs forever and never spins up the server.

**Comment by johndevs** [comment]
Hi,

Hard to say, a couple of generic things to try is removing the gwt-UnitCache from the webapp folder (if are compiling your own widgetset)  and then run with the --info flag and see if you can get some more details.

**Comment by yissachar** [comment]
Some more info:

With the default Payara server it seems some part of the server is spun up, but not linked to the app.  The plugin never triggers an open in browser, but manually hitting localhost:8080 returns a 404 (whereas if the plugin is not running, this would just timeout).

Switching the server to Jetty gets me a bit further. The plugin triggers an open in browser event, which takes me to my app's homepage as I would expect. However, from there things don't work properly - every attempt to do anything hangs, and it seems like the Vaadin push events are not completing.

Removing gwt-UnitCache had no effect.

**Comment by johndevs** [comment]
Have you enabled push?
```
vaadin.push = true
```
