### ISSUE TITLE
Need version compatible with Gradle 3.0

### ISSUE THREAD

**Issue by rsivan** [johndevs/gradle-vaadin-plugin#265]
Today I experimented with Gradle 3.0. It turns out my scripts fail due to this plugin not having compatibility with Gradle 3.0.
Do you have plans to support it?
Thanks

**Comment by johndevs** [comment]
Hi, 

Could you describe what is not working for you with Gradle 3.0?

At least a simple test run with ``$> gradle vaadinCreateProject vaadinRun`` seems to work without problems on Gradle 3.0.

**Comment by rsivan** [comment]
Sorry, I was not paying attention, I just tried again with the most recent version of Gradle, 3.1, same error:
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rsivan/pv/pvtrunk/Src/Modules/Pv3Widgetset/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':Modules:Pv3Widgetset'.
> Failed to apply plugin [id 'fi.jasoft.plugin.vaadin']
   > Your gradle version (3.1) is too old. Plugin requires Gradle 2.0+

**Comment by rsivan** [comment]
My bad, 0.11.4 does support 3.x, I was using an older version
