### ISSUE TITLE
vaadin.manageDependencies = false stopped working in plugin version 0.11

### ISSUE THREAD

**Issue by bc15** [johndevs/gradle-vaadin-plugin#267]
vaadin.manageDependencies = false stopped working in plugin version 0.11.
In 0.10.7 it works as it should, but in 0.11+ the dependencies get pulled (wrong jars can be seen in eclipse under Web App Libraries), even if vaadin.manageDependencies is set to false.
I use gradle version 2.14.1 on Windows 7 64 bit and Eclipse Neon.

**Comment by johndevs** [comment]
Hi,

Tried to reproduce this with the following simple build script:
```gradle
plugins {
  id "fi.jasoft.plugin.vaadin" version "0.11.1"
}
vaadin.manageDependencies = false
```
and I get the following output:
```
/t/test $ gradle dependencies
Using Gradle Vaadin Plugin 0.11.1
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

archives - Configuration for archive artifacts.
No dependencies

compile - Dependencies for source set 'main'.
No dependencies

compileClasspath - Compile classpath for source set 'main'.
No dependencies

compileOnly - Compile dependencies for source set 'main'.
No dependencies

default - Configuration for default artifacts.
No dependencies

providedCompile - Additional compile classpath for libraries that should not be part of the WAR archive.
No dependencies

providedRuntime - Additional runtime classpath for libraries that should not be part of the WAR archive.
No dependencies

runtime - Runtime dependencies for source set 'main'.
No dependencies

testCompile - Dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
No dependencies

testCompileOnly - Compile dependencies for source set 'test'.
No dependencies

testRuntime - Runtime dependencies for source set 'test'.
No dependencies

BUILD SUCCESSFUL

Total time: 1.47 secs
```
So looks like ``manageDependencies`` is working at least for this case.

You could check the following things
* Run the clean and cleanEclipse tasks on your project
* Ensure Vaadin is not getting pulled in as  a transitive dependency of another dependency you have in your build
* Ensure that your Eclipse configuration is up to date, press the "Refresh Gradle Build" button to refresh the project
