### ISSUE TITLE
Error in a multiproject build

### ISSUE THREAD

**Issue by mkanada** [johndevs/gradle-vaadin-plugin#271]
I have a root gradle project with some subprojects. Only one of these subprojects uses the vaadin gradle plugin. Since last update, the build fails.

I created a simple example that you can download in link below.

https://drive.google.com/open?id=0B4gZr59r9LNKV0w4cXB5enhsNmM

Thanks a lot for this so great plugin.

**Comment by johndevs** [comment]
Hi, 

Thanks for the excellent bug report! 

I fixed the issue and released a new version ``0.11.4`` where this hopefully should be fixed.
