### ISSUE TITLE
Add-on with client side code not working

### ISSUE THREAD

**Issue by geld0r** [johndevs/gradle-vaadin-plugin#279]
I am trying to use this plugin with Spring-Boot-Vaadin in order to compile a widgetset so that I can use a Vaadin [add-on](https://github.com/downdrown/VaadinHighChartsAPI) with client side code in my app.
I am using Vaadin 7.7.0

I've never done that before and followed the documentation, specifically [this ](https://github.com/johndevs/gradle-vaadin-plugin/wiki/Using-addons#addons-with-client-side-code) part.

However the widgetset doesn't seem to be detected upon start. Adding `@Widgetset("AppWidgetset")` also didn't change this. The page that makes use of the charts provided by the add-on remain empty and the loading bar suggests that something is still being loaded.

After generating or updating the widgetset, the add-on doesn't show up there (if I am not mistaken, it should). If I add it manually, the following error occurs:

> Unable to find 'at/downdrown/vaadinaddons/highchartsapi/WidgetSet.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

The add-on is declared in my build.gradle:

> compile "at.downdrown.vaadinaddons:highchartsapi:2.2.1-QF"

Am I missing something?

**Comment by johndevs** [comment]
Hi,

I'm not familar with that specific addon but I took a look at the addon jar contents and it only consists of server side classes and Javascript. So no client side GWT code and it doesn't include any Widgetset.gwt.xml file. So you will not need to compile the widgetset for this addon and the addon should work with the standard Vaadin widgetset. 

Maybe some earlier version of the addon has needed a widgetset but later the author has decided to implement the client side in pure javascript?

**Comment by geld0r** [comment]
Hi,

thanks for having a look that quickly. Looking at the release [history ](https://github.com/downdrown/VaadinHighChartsAPI/releases) it seems plausible that the build was changed quite a lot.

This is probably not an issue with this plugin then. Maybe VaadinHighChartsAPI doesn't fit with setup (e.g. vaadin-push is used). I'll try to look into that direction.
Thanks again for having a look!

**Comment by johndevs** [comment]
I'm closing this as this is not related to the plugin.
