### ISSUE TITLE
Using cloud compilation fails

### ISSUE THREAD

**Issue by mstahv** [johndevs/gradle-vaadin-plugin#280]
The error in log is:

```
[ERROR] Error: Could not find or load main class com.google.gwt.dev.Compiler
```

Also the wiki page contains some broken links? The configuration property is mentioned [here](https://github.com/johndevs/gradle-vaadin-plugin/wiki/Tasks-and-configuration-DSL) but the ToC contains just broken link.

**Comment by mstahv** [comment]
Let me know when the release is out, I'll tweet about it with vaadin account!

**Comment by johndevs** [comment]
@mstahv The release is now out! :santa:
