### ISSUE TITLE
Documentation : Show How To Supply Parameters To Tasks

### ISSUE THREAD

**Issue by canthony** [johndevs/gradle-vaadin-plugin#281]
It's probably just me, and my lack of Gradle knowledge - but it isn't immediately obvious how to pass parameters to the tasks.

Having had to look this up at this three separate times for three different prototype projects I've been working at over the last few months, I figure it's worth mentioning!

For example, the vaadinCreateTheme tasks takes a single parameter 'name'. To specify the name, you need to provide it on the command line after the task name, prefixed with two hypens. e.g.
```
gradle vaadinCreateTheme --name=a-funky-new-theme
```
I suppose the best place to put this info would be in the top of the [Tasks-and-configuration-DSL](https://github.com/johndevs/gradle-vaadin-plugin/wiki/Tasks-and-configuration-DSL) page.

I would have updated the Wiki if I could have - but forking the repo doesn't appear to bring the Wiki with it, so I couldn't do a pull-request. Again, probably just me being a bit rubbish and not knowing enough about GitHub.

**Comment by johndevs** [comment]
Excellent idea! 

Github provides the wiki is a separate repository https://github.com/johndevs/gradle-vaadin-plugin.wiki.git (the link is well hidden in the bottom right corner under the TOC). 

If you still want to make that PR I would appreciate it :+1:

**Comment by canthony** [comment]
I can't see how to make a proper PR for the wiki, as I can't "fork" the Wiki Repo. 

So, I've 
 * cloned the repo locally,
 * created a topic branch `281-document-supplying-parameters`
 * updated the markdown document, and committed to the branch
 * pushed it to my GitHub account https://github.com/canthony/gradle-vaadin-plugin-wiki

And you can find the branch [here](https://github.com/canthony/gradle-vaadin-plugin-wiki/tree/281-document-supplying-parameters) . How you merge the branch into the main Wiki repo is left as an exercise for the reader! 

\<grumble\>GitHub's Wiki appears to be a massive PITA, and not really a Wiki at all! \</grumble\>

**Comment by johndevs** [comment]
Oh, you are absolutely right, apparently you can't fork the wiki repository and so can't make PR. Looks like the wiki is not yet very usable :(

Anyway, you've made it easy for me to just merge the branch so it shouldn't be harder than applying a normal PR. Thanks for this, I appreciate it!

**Comment by johndevs** [comment]
Change was merged in https://github.com/johndevs/gradle-vaadin-plugin/wiki/Tasks-and-configuration-DSL/_compare/ef6d7af
