### ISSUE TITLE
Renaming project packages

### ISSUE THREAD

**Issue by neopsis** [johndevs/gradle-vaadin-plugin#282]
I am sure I am missing anything obvious but ... I must rename my project packages. Using JetBrains Idea the refactoring was easy but now vaadinRun does work anymore. The server returns internal error complaining the UI class cannot be found.  When I return back to the old package names, everything works. 
What should I do additionally to Java refactoring to be able to run the app on the intergated server using vaadnRun?

**Comment by neopsis** [comment]
OK, I got it. 

`@WebInitParam(name="ui", value="must.be.fully.qualified.ClassName")`

Task vaadinCreateProject generates value="ClassName", which is fine to start with HelloWorld example but fails after package rename. Maybe enhancement for the project generator.

**Comment by johndevs** [comment]
The project generator just generates the sample project, it will not verify any changes after that. So it is up to the one who is refactoring (many IDE's will do this for you) to ensure the package refactoring also refactors package string names. 

In Idea this can be done by checking the box "search in strings and comments" when invoking the refactoring.
