### ISSUE TITLE
Vaadin 8 compability

### ISSUE THREAD

**Issue by zotona** [johndevs/gradle-vaadin-plugin#284]
Is planed to support vaadin 8? is it possible to get support with current version?

**Comment by christoph-frick** [comment]
Could you please add what problems you are facing?  Version 1.0 with Vaadin 8 alpha 6 Works Fine For Me™

**Comment by zotona** [comment]
thanks for response. i tried 1.0, but vaadinCompile task fails at:
Unable to find 'com/vaadin/terminal/gwt/DefaultWidgetSet.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source

my gradle 
````
dependencyManagement {
	imports {
		mavenBom "com.vaadin:vaadin-bom:$vaadinVersion"
	}
}
vaadin {
	manageDependencies false
	mainSourceSet sourceSets.main.groovy
}

vaadinCompile {
	userAgent 'ie8,ie9,ie10,gecko1_8,safari'
	gwtSdkFirstInClasspath false
	manageWidgetset false
	widgetset 'AppWidgetset'
}

compile group: 'com.vaadin', name: 'vaadin-push'
	compile group: 'com.vaadin', name: 'vaadin-shared'
	compile group: 'com.vaadin', name: 'vaadin-client-compiled'
	compile group: 'com.vaadin', name: 'vaadin-compatibility-server'
````

**Comment by zotona** [comment]
Error ``Unable to find 'com/vaadin/terminal/gwt/DefaultWidgetSet.gwt.xml' on your classpath`` happened, when some widget made for old version of vaadin. If it removed, this error is gone.
