### ISSUE TITLE
Plugin breaks non-vaadin jar artifacts in multi-project build

### ISSUE THREAD

**Issue by gwyn** [johndevs/gradle-vaadin-plugin#287]
In multi-project builds with the plugin applied at the top-level, the jar task of all sub projects will be enhanced to add Vaadin manifest modifications. This breaks sub project jars in my specific case as they must not contain Vaadin data. I tracked the problem to TaskListener class. The check `task.project.hasProperty('vaadin')` seems to be true even for non Vaadin sub projects (looks like extension properties are somehow automatically inherited).

There seems to be no way to work around this from the outside (gradle does not permit removing extension properties). I fixed it by checking if the plugin is applied or not instead:

```groovy
    public static final String VAADIN_PLUGIN_NAME = 'fi.jasoft.plugin.vaadin'

    public void beforeExecute(Task task) {
        if (!task.project.pluginManager.hasPlugin(VAADIN_PLUGIN_NAME)) {
            return
        }
        [...]
    }

    public void afterExecute(Task task, TaskState state) {
        if (!task.project.pluginManager.hasPlugin(VAADIN_PLUGIN_NAME)) {
            return
        }
        [...]
    }
```
I think this is actually the correct way to go. After all, plugins should only affect projects they are applied to.

**Comment by johndevs** [comment]
Hi, 

You're absolutely right, the plugin should not alter project artifacts that does not have the plugin applied. The fix looks ok with me, I'll add it for the next maintenance version.

Thanks!
