### ISSUE TITLE
Issue in gradle file

### ISSUE THREAD

**Issue by thomaspp** [johndevs/gradle-vaadin-plugin#300]
Hello all,

since the new version 1.1, I receive an error by updating the project:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Thomas\workspace_neon\lunchlist\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'lunchlist'.
Failed to apply plugin [id 'fi.jasoft.plugin.vaadin']
 Could not generate a proxy class for class fi.jasoft.plugin.tasks.CompileWidgetsetTask.

My build.gradle is the following:

buildscript {
	repositories {
	    mavenCentral()
	    maven { url "https://plugins.gradle.org/m2/" }
	    maven { url "http://oss.sonatype.org/content/repositories/vaadin-snapshots/" }
	    maven { url "http://maven.vaadin.com/vaadin-addons" }
	}
    
       dependencies {
           classpath("fi.jasoft.plugin:gradle-vaadin-plugin:+")
           classpath("org.springframework.boot:spring-boot-gradle-plugin:+")
       }
}

apply plugin: 'war'
apply plugin: 'java'
apply plugin: 'eclipse-wtp'
apply plugin: 'org.springframework.boot'
apply plugin: 'fi.jasoft.plugin.vaadin'

Does anyone have an idea what is the problem?

Best Regards,
Thomas

... sorry for the stupid formatting... ;-(

**Comment by johndevs** [comment]
Sounds like a corrupted gradle environment. 

Could you delete the ``.gradle`` folder in the project and re-run? Also ensure you are using Gradle 3.x.

If it persists run gradle with the ``--info`` and ``--stacktrace``  command line options so we'll get a full stacktrace of where the issue occurs.

**Comment by dhhyi** [comment]
I'm also experiencing this issue since gradle-vaadin-plugin 1.1.
The reason seems to be a missing class (groovyx.net.http.RESTClient). Adding 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1' to buildscript classpath dependencies solved this issue for me.

Downgrading to gradle-vaadin-plugin 1.0.1 might also work

**Comment by johndevs** [comment]
@dhhyi:
> The reason seems to be a missing class (groovyx.net.http.RESTClient). Adding 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1' to buildscript classpath dependencies solved this issue for me.

Are you serving the plugin from an internal repository? RestClient is a dependency of the plugin, but it should be automatically resolved if you are using the standard repositories as the plugin's pom.xml has a dependency to it (https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/gradle-vaadin-plugin-1.1.pom). If you are serving if from an internal repository remember to include the pom.xml file as well as the jar artifact.

**Comment by vyazelenko** [comment]
The metadata of the release 1.1 is broken. If you have a look at [1.1 release files](https://bintray.com/johndevs/maven/gradle-vaadin-plugin/1.1#files/fi/jasoft/plugin/gradle-vaadin-plugin/1.1) you'll see that [gradle-vaadin-plugin-1.1.pom](https://bintray.com/johndevs/maven/download_file?file_path=fi%2Fjasoft%2Fplugin%2Fgradle-vaadin-plugin%2F1.1%2Fgradle-vaadin-plugin-1.1.pom) has the following contents:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fi.jasoft.plugin</groupId>
  <artifactId>gradle-vaadin-plugin</artifactId>
  <version>1.1</version>
  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>johndevs</id>
      <name>John Ahlroos</name>
    </developer>
  </developers>
  <scm>
    <connection>scm:git://github.com/johndevs/gradle-vaadin-plugin</connection>
    <developerConnection>scm:git@github.com:johndevs/gradle-vaadin-plugin</developerConnection>
    <url>https://github.com/johndevs/gradle-vaadin-plugin</url>
  </scm>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.groovy.modules.http-builder</groupId>
      <artifactId>http-builder</artifactId>
      <version>0.7.1</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
```
And from the above `http-builder` dependency has type `pom`?!

**Comment by dhhyi** [comment]
I'm using an external repository. https://jcenter.bintray.com/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/gradle-vaadin-plugin-1.1.jar is used. http-builder is listed as pom-dependency in the corresponding plugin POM. Maybe that's why...

**Comment by vyazelenko** [comment]
@johndevs What is also interesting is that URL [https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/gradle-vaadin-plugin-1.1.pom](https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/gradle-vaadin-plugin-1.1.pom) returns *correct* POM file. But if you try to use [https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/](https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/) you will be automatically redirected to [https://jcenter.bintray.com/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/](https://jcenter.bintray.com/fi/jasoft/plugin/gradle-vaadin-plugin/1.1/) which contains broken POM file definition.

**Comment by johndevs** [comment]
@vyazelenko I think that has to do with that previously Gradle's plugin portal used to depend on Bintray to serve the artifacts and currently the build is now deploying to both Bintray *and* Gradle's plugin portal. Lets remote the Bintray deployment and it should work better.

**Comment by thomaspp** [comment]
Hello,

Good to hear that I was not the only one ;-)

I tested it again and now the following error occured:

---------------------------
Using Gradle Vaadin Plugin 1.1.patch300

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'lunchlist'.
> Could not resolve all dependencies for configuration ':vaadin-run-server'.
   > Could not find fi.jasoft.plugin:gradle-vaadin-plugin:1.1.patch300.
     Searched in the following locations:
         https://repo1.maven.org/maven2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.pom
         https://repo1.maven.org/maven2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.jar
         file:/C:/Users/Thomas/.m2/repository/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.pom
         file:/C:/Users/Thomas/.m2/repository/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.jar
         http://maven.vaadin.com/vaadin-addons/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.pom
         http://maven.vaadin.com/vaadin-addons/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.jar
         http://oss.sonatype.org/content/repositories/vaadin-snapshots/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.pom
         http://oss.sonatype.org/content/repositories/vaadin-snapshots/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.jar
         https://maven.vaadin.com/vaadin-prereleases/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.pom
         https://maven.vaadin.com/vaadin-prereleases/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.patch300/gradle-vaadin-plugin-1.1.patch300.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
---------------------------

Regards,
Thomas

**Comment by johndevs** [comment]
@thomaspp Thanks for testing out the patch release! :)

But please try the newly released "1.1.patch300.2" release. The one you tried was missing the Gradle portal plugin a repository definition. I'll build a new real release (1.1.1) once we know this works.

**Comment by thomaspp** [comment]
Perfect, now it works! :-)

Thanks a lot!

**Comment by thomaspp** [comment]
Still the same problem with 1.1.1? ;-)

* What went wrong:
A problem occurred configuring root project 'lunchlist'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find fi.jasoft.plugin:gradle-vaadin-plugin:1.1.1.
     Searched in the following locations:
         https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.1/gradle-vaadin-plugin-1.1.1.pom
         https://plugins.gradle.org/m2/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.1/gradle-vaadin-plugin-1.1.1.jar
         http://oss.sonatype.org/content/repositories/vaadin-snapshots/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.1/gradle-vaadin-plugin-1.1.1.pom
         http://oss.sonatype.org/content/repositories/vaadin-snapshots/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.1/gradle-vaadin-plugin-1.1.1.jar
         http://maven.vaadin.com/vaadin-addons/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.1/gradle-vaadin-plugin-1.1.1.pom
         http://maven.vaadin.com/vaadin-addons/fi/jasoft/plugin/gradle-vaadin-plugin/1.1.1/gradle-vaadin-plugin-1.1.1.jar
     Required by:
         project :

**Comment by johndevs** [comment]
@thomaspp 1.1.1 has not been built yet ;)

**Comment by johndevs** [comment]
@thomaspp Now 1.1.1 is released :relaxed:

**Comment by thomaspp** [comment]
top :)
