### ISSUE TITLE
ConnectorBundleLoaderFactory module not found on classpath

### ISSUE THREAD

**Issue by johndevs** [johndevs/gradle-vaadin-plugin#305]
Looks like the ConnectorBundleLoaderFactory is not included on the GWT compilers classpath.

```
Errors in 'file:/tmp/test/src/main/java/com/example/client/ui/MyWidgetsetGenerator.java'
Line 12: No source code is available for type com.vaadin.server.widgetsetutils.ConnectorBundleLoaderFactory; did you forget to inherit a required module?
Line 37: No source code is available for type com.google.gwt.core.ext.typeinfo.JClassType; did you forget to inherit a required module?
Aborting compile due to errors in some input files
```

**Comment by johndevs** [comment]
This only occurs if you place the Generator class *inside* the client package and the GWT compiler picks it up. We should fail the build if you try to do that so it is clear what is happening.

**Comment by thomaspp** [comment]
Thanks for the fast response! 

This means I have to put it for example into file:/tmp/test/src/main/java/com/example/MyWidgetsetGenerator.java?

But this is generated automatically? Is it possible tc change it anyway?

**Comment by johndevs** [comment]
> This means I have to put it for example into file:/tmp/test/src/main/java/com/example/MyWidgetsetGenerator.java?

Yes, that should work.

> But this is generated automatically? Is it possible tc change it anyway?

Yes, it is only generated when you run **vaadinCreateWidgetsetGenerator**. After that you can move it or change it however you like. Just remember to update ``vaadinCompile.widgetsetGenerator = 'com.example.MyWidgetsetGenerator ' `` in your *build.gradle* when you move it to another location.

**Comment by thomaspp** [comment]
Ok, perfect. I think it is working...

Is there a way to check whether the new generator is used?

**Comment by thomaspp** [comment]
Hello!

vaadinCompile finishs without any error. But executing bootRepackage still shows some errors related to the widgetset generator. But it seems that it is related to javaDoc:

:javadocC:\Users\Thomas\workspace_neon\lunchlist\src\main\java\de\lunchlist\frontend\LunchlistWidgetsetGenerator.java:6: error: package com.google.gwt.core.ext.typeinfo does not exist
import com.google.gwt.core.ext.typeinfo.JClassType;
                                       ^
C:\Users\Thomas\workspace_neon\lunchlist\src\main\java\de\lunchlist\frontend\LunchlistWidgetsetGenerator.java:7: error: cannot find symbol
import com.vaadin.server.widgetsetutils.ConnectorBundleLoaderFactory;
                                       ^
  symbol:   class ConnectorBundleLoaderFactory
  location: package com.vaadin.server.widgetsetutils
C:\Users\Thomas\workspace_neon\lunchlist\src\main\java\de\lunchlist\frontend\LunchlistWidgetsetGenerator.java:10: error: cannot find symbol
public class LunchlistWidgetsetGenerator extends ConnectorBundleLoaderFactory {
                                                 ^
  symbol: class ConnectorBundleLoaderFactory
C:\Users\Thomas\workspace_neon\lunchlist\src\main\java\de\lunchlist\frontend\LunchlistWidgetsetGenerator.java:30: error: cannot find symbol
	protected LoadStyle getLoadStyle(JClassType connectorType) {
	                                 ^
  symbol:   class JClassType
  location: class LunchlistWidgetsetGenerator
javadoc: error - com.sun.tools.doclets.internal.toolkit.util.DocletAbortException: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for javax.interceptor.InterceptorBinding not found

**Comment by thomaspp** [comment]
Another question: Is it possible two have two WidgetSets (for different UIs, e.g. mobile/desktop) and create therefore two different WidgetsetGenerator? I'm aksing because I define in the build.gradle the widgetset and the generator?

**Comment by johndevs** [comment]
@thomaspp 
> vaadinCompile finishs without any error. But executing bootRepackage still shows some errors related to the widgetset generator. But it seems that it is related to javaDoc:

The Javadoc error in the next maintenance release.

> Another question: Is it possible two have two WidgetSets (for different UIs, e.g. mobile/desktop) and create therefore two different WidgetsetGenerator? I'm aksing because I define in the build.gradle the widgetset and the generator?

If you want to have multiple widgetsets then you should split your application up into multiple modules that all build their own widgetset. All modules have their own build.gradle file where you can define different parameters for ``vaadinCompile``.
