### ISSUE TITLE
Allow theme CSS to be compressed

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#307]
Hi John, Happy New Year and all the best! ;)

Could you please add a configuration option for the theme compiler to compress the theme to gzip as it is possible with the Maven plugin: `<compressTheme>true</compressTheme>` https://github.com/vaadin/sass-compiler/issues/297
Note that minify does not need to be supported as the size savings are not that relevant (discussed at https://github.com/vaadin/sass-compiler/issues/93 ), so gzipping the styles.css to styles.css.gz is completely enough.

**Comment by johndevs** [comment]
Hi, this will be added in the release :)

**Comment by mvysny** [comment]
Thank you so much, I owe you a beer ;)
