### ISSUE TITLE
Cannot cast object 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated@1a0c6406' with class 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'

### ISSUE THREAD

**Issue by canthony** [johndevs/gradle-vaadin-plugin#313]
When trying to configure the Test Task, Gradle Is Falling over the error message.

```
Cannot cast object 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated@1a0c6406' with class 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'
```
I've no idea how to go about tracking this one down... Unfortunately, this is tricky to isolate, as this is a multi-module build - and I'm trying to move the Vaadin Theme Compile and Vaadin Compilation into separate modules, as per your helpful post in Vaadin Forum. 

I can't post the source of all of the build here, unfortunately; I've attached the log, and the failing modules build.gradle, too.

If I revert to before trying to move the compilations into separate modules, the above doesn't occur.

Have you seen this before, and have you got any guidance on this? 

Gradle : 3.3
Vaadin Gradle Plugin 1.1.1

[build-error.log.txt](https://github.com/johndevs/gradle-vaadin-plugin/files/707987/build-error.log.txt)
[module-build.gradle.txt](https://github.com/johndevs/gradle-vaadin-plugin/files/708018/module-build.gradle.txt)

**Comment by canthony** [comment]
OK; I think I've tracked the problem down. If I load the plugin via the plugin container mechanism in the - root project i.e.

```
plugins {
    id 'fi.jasoft.plugin.vaadin' version '1.1.1' apply false
}
````
and then apply it in the sub project, it all works fine.

If I load the plugin in the sub projects using 
```
buildscript {
  dependencies {
    classpath("fi.jasoft.plugin:gradle-vaadin-plugin:1.1.1")
  }
}
```
Then the classcast problem occurs. At a guess, this is possibly applying more than once (once for each occurence on the classpath??).

 I don't know.

The reason we were going with the buidscript/dependencies approach is that this allowed us to specify the version using a single variable in the root project, and load the plugins using that variable; you can't use variables with the plugins container approach.

Howeverm, I now see that, by using ```plugins {plugin 'id' version 'version' apply false}``` you can load the plugin in the root project, and not apply it.

I think this will work for us... Still - "interesting" problem as to why it wasn't working with the other approach.

Cheers.

Charles.

**Comment by johndevs** [comment]
@canthony Thanks for posting the followup! I think I can write a test case out of it now and fix it. Was wondering how to reproduce that one :)

The code in the ``TaskListener`` at that point doesn't look right, it should get the configuration via ``project.extensions`` rather than straight from the plugin root. Should be easy to fix.

**Comment by johndevs** [comment]
Hopefully fixed now.
