### ISSUE TITLE
The Jetty launcher classpath may not be complete

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#318]
I have troubles launching a sample project in Payara #315 so I thought I would try Jetty. However, it didn't worked out quite well: the persistence provider generally complains that it cannot find the persistence unit. The curious thing is the following console output:
```
Jan 17, 2017 1:11:25 PM org.hibernate.jpa.boot.internal.PersistenceXmlParser doResolve
INFO: HHH000318: Could not find any META-INF/persistence.xml file in the classpath
```
The file is present in src/main/resources/META-INF, so maybe it is not on Jetty's classpath for some reason?
I'm attaching the testing project - just run `./gradlew vaadinRun` on it.
[myvaadinapp.zip](https://github.com/johndevs/gradle-vaadin-plugin/files/710825/myvaadinapp.zip)

**Comment by johndevs** [comment]
Thanks, indeed the resources was not included properly on Jetty's classpath. That should be fixed now and the provided app should work with the next version of the plugin (provided you rememebr to add the Person bean to persistance.xml :wink: ).
