### ISSUE TITLE
Make plugin Spring Boot aware

### ISSUE THREAD

**Issue by johndevs** [johndevs/gradle-vaadin-plugin#325]
When Spring Boot plugin is added to the build, the Vaadin plugin should add the relevant classpaths to the plugin so the user does not need to. The following needs to be done by the plugin:

1) Add classpath entries to *bootRun:
```
bootRun {
    classpath += configurations['vaadin-server']
    classpath += configurations['vaadin-client']
}
```
2) Add compile dependencies
```
bootRun {
    dependsOn 'vaadinCompile', 'vaadinThemeCompile'
}
```
3) Configure *jar*-task to include *webapp*
```
jar { 
    from 'src/main/webapp'
}
```
4) Add dependency to Vaadin Spring Boot 
```
dependencies {
    compile 'com.vaadin:vaadin-spring-boot-starter:2.0-SNAPSHOT'
}
```

**Comment by christoph-frick** [comment]
Just to mention it, this is the route I usually go: https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/gradle/springboot-vaadin-fixes.gradle

Also I have to remove deps, that pull in `validation-api 1.1` into the `vaadin-client` config (Useful not only for springboot): https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/build.gradle#L87-L95
