### ISSUE TITLE
Springboot 1.5 seems to force validation-api 1.1 in the `vaadin-client` configuration

### ISSUE THREAD

**Issue by christoph-frick** [johndevs/gradle-vaadin-plugin#326]
Updating my project from springboot 1.4.4 to 1.5.1 breaks compilation of the widgetset.  It fails because the validation api 1.1 overrides the 1.0.0.GA in the `vaadin-client` configuration.  In the past I needed to exclude all the deps, that pull in the validation-api (which seems no longer needed with recent versions of the gradle vaadin plugin). So I tried some things with the resolutionStrategy, but no luck

I use this repo for testing: https://github.com/christoph-frick/springboot-groovy-vaadin-starter/tree/wip-spring-boot-1.5

Those are the changes I tried: https://github.com/christoph-frick/springboot-groovy-vaadin-starter/commit/301a1353c1b8ab92626e47402e9f5b7c59e05695

The deps for `vaadin-client` look like this:

    vaadin-client - Libraries needed for compiling the widgetset.
    +--- com.vaadin:vaadin-client:7.7.6
    |    +--- com.vaadin:vaadin-shared:7.7.6
    |    +--- com.vaadin:vaadin-server:7.7.6
    |    |    +--- com.vaadin:vaadin-shared:7.7.6
    |    |    \--- org.jsoup:jsoup:1.8.3
    |    \--- com.vaadin.external.gwt:gwt-elemental:2.7.0.vaadin4
    |         \--- com.vaadin.external.gwt:gwt-user:2.7.0.vaadin4
    |              \--- javax.validation:validation-api:1.0.0.GA -> 1.1.0.Final
    +--- com.vaadin:vaadin-client-compiler:7.7.6
    |    +--- com.vaadin:vaadin-client:7.7.6 (*)
    |    +--- com.vaadin.external.gwt:gwt-dev:2.7.0.vaadin4
    |    |    +--- org.ow2.asm:asm:5.0.3
    |    |    +--- org.ow2.asm:asm-util:5.0.3
    |    |    |    \--- org.ow2.asm:asm-tree:5.0.3
    |    |    |         \--- org.ow2.asm:asm:5.0.3
    |    |    \--- org.ow2.asm:asm-commons:5.0.3
    |    |         \--- org.ow2.asm:asm-tree:5.0.3 (*)
    |    \--- com.vaadin:vaadin-sass-compiler:0.9.13
    |         +--- org.w3c.css:sac:1.3
    |         +--- com.vaadin.external.flute:flute:1.3.0.gg2
    |         \--- com.yahoo.platform.yui:yuicompressor:2.4.8
    |              \--- rhino:js:1.7R2
    \--- javax.validation:validation-api:1.0.0.GA -> 1.1.0.Final

Build fails at `vaadinCompile` with:

    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/ParameterNameProvider.java'
    Line 54: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
    Line 44: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
    Tracing compile failure path for type 'javax.validation.executable.ExecutableValidator'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/executable/ExecutableValidator.java'
    Line 53: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
    Line 94: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.GwtValidatorContext'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/GwtValidatorContext.java'
    Line 29: The type GwtValidatorContext must implement the inherited abstract method ValidatorContext.parameterNameProvider(ParameterNameProvider)
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.GwtBeanDescriptorImpl'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/GwtBeanDescriptorImpl.java'
    Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstraintsForConstructor(Class<?>...)
    Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstrainedConstructors()
    Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstraintsForMethod(String, Class<?>...)
    Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstrainedMethods(MethodType, MethodType...)
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
    Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
    Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/PropertyDescriptorImpl.java'
    Line 31: The type PropertyDescriptorImpl must implement the inherited abstract method CascadableDescriptor.getGroupConversions()
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.NodeImpl'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/NodeImpl.java'
    Line 25: The type NodeImpl must implement the inherited abstract method Path.Node.as(Class<T>)
    Line 25: The type NodeImpl must implement the inherited abstract method Path.Node.getKind()
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintValidatorContextImpl'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/ConstraintValidatorContextImpl.java'
    Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addPropertyNode(String)
    Line 39: The type ConstraintValidatorContextImpl<A,T> must implement the inherited abstract method ConstraintValidatorContext.unwrap(Class<T>)
    Line 112: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderDefinedContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderDefinedContext.addPropertyNode(String)
    Line 79: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderCustomizableContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderCustomizableContext.addBeanNode()
    Line 79: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderCustomizableContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderCustomizableContext.addPropertyNode(String)
    Line 112: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderDefinedContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderDefinedContext.addBeanNode()
    Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addParameterNode(int)
    Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addBeanNode()
    Line 142: The type ConstraintValidatorContextImpl<A,T>.NodeContextBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeContextBuilder.addBeanNode()
    Line 142: The type ConstraintValidatorContextImpl<A,T>.NodeContextBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeContextBuilder.addPropertyNode(String)
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintViolationImpl'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/ConstraintViolationImpl.java'
    Line 30: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.getExecutableReturnValue()
    Line 30: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.unwrap(Class<U>)
    Line 30: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.getExecutableParameters()
    Tracing compile failure path for type 'com.google.gwt.validation.client.GwtConstraintValidatorFactory'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/GwtConstraintValidatorFactory.java'
    Line 26: The type GwtConstraintValidatorFactory must implement the inherited abstract method ConstraintValidatorFactory.releaseInstance(ConstraintValidator<?,?>)
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.PropertyDescriptorImpl'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/PropertyDescriptorImpl.java'
    Line 31: The type PropertyDescriptorImpl must implement the inherited abstract method CascadableDescriptor.getGroupConversions()
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
    Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
    Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
    Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintDescriptorImpl'
    Errors in 'jar:file:/home/ridcully/.gradle/caches/modules-2/files-2.1/com.vaadin.external.gwt/gwt-user/2.7.0.vaadin4/926666000e33edcc06604a6a19c65e9cfe7ca6df/gwt-user-2.7.0.vaadin4.jar!/com/gclient/impl/ConstraintDescriptorImpl.java'
    Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
    Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
    Aborting compile due to errors in some input files
    :vaadinCompile FAILED

**Comment by johndevs** [comment]
@christoph-frick In https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/wip-spring-boot-1.5/build.gradle#L90 you are replacing the plugins default resolution strategy (https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/fi/jasoft/plugin/GradleVaadinPlugin.groovy#L494) with your own which does not account for all the things the plugins resolution strategy accounts for. If you remove your own resolution strategy, does it then work?

**Comment by christoph-frick** [comment]
Nope this was just another attempt to make it work.  This block does not exist, when I use it with 1.4.  See https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/build.gradle

**Comment by lschaffer** [comment]
I can confirm this with Spring boot 1.5.1 the widgetset cannot be compiled

**Comment by johndevs** [comment]
@lschaffer Hi, yes this will get fixed among other issues with Spring Boot in ``1.1.3``.

**Comment by dirkm** [comment]
I am using `gradle-vaadin-plugin 1.1.6` with `spring-boot 1.5.2` , and I am still observing this issue:

```
vaadin-client - Libraries needed for compiling the widgetset.
+--- com.vaadin:vaadin-client:7.7.7
|    +--- com.vaadin:vaadin-shared:7.7.7
|    +--- com.vaadin:vaadin-server:7.7.7
|    |    +--- com.vaadin:vaadin-shared:7.7.7
|    |    \--- org.jsoup:jsoup:1.8.3
|    \--- com.vaadin.external.gwt:gwt-elemental:2.7.0.vaadin4
|         \--- com.vaadin.external.gwt:gwt-user:2.7.0.vaadin4
|              \--- javax.validation:validation-api:1.0.0.GA -> 1.1.0.Final
+--- com.vaadin:vaadin-client-compiler:7.7.7
|    +--- com.vaadin:vaadin-client:7.7.7 (*)
|    +--- com.vaadin.external.gwt:gwt-dev:2.7.0.vaadin4
|    |    +--- org.ow2.asm:asm:5.0.3
|    |    +--- org.ow2.asm:asm-util:5.0.3
|    |    |    \--- org.ow2.asm:asm-tree:5.0.3
|    |    |         \--- org.ow2.asm:asm:5.0.3
|    |    \--- org.ow2.asm:asm-commons:5.0.3
|    |         \--- org.ow2.asm:asm-tree:5.0.3 (*)
|    \--- com.vaadin:vaadin-sass-compiler:0.9.13
|         +--- org.w3c.css:sac:1.3
|         +--- com.vaadin.external.flute:flute:1.3.0.gg2
|         \--- com.yahoo.platform.yui:yuicompressor:2.4.8
|              \--- rhino:js:1.7R2
\--- javax.validation:validation-api:1.0.0.GA -> 1.1.0.Final
```

The only workaround I could come up with is symlinking 

```
$ ~/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090$ ls -l
lrwxrwxrwx 1 dirk dirk 91 mars  27 10:21 validation-api-1.1.0.Final-sources.jar -> ../../1.0.0.GA/7a561191db2203550fbfa40d534d4997624cd369/validation-api-1.0.0.GA-sources.jar
```

but that is very ugly, of course.

**Comment by johndevs** [comment]
Are you perhaps overriding the resolutionStrategy for ``vaadin-client``?

**Comment by dirkm** [comment]
I am forcing on old tomcat-version, but that should be completely unrelated, right? Does this affect vaadin-client?

```
    configurations.all {
      resolutionStrategy {
         force "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"
         force "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}"
         force "org.apache.tomcat.embed:tomcat-embed-logging-log4j:${tomcatVersion}"
         force "org.apache.tomcat.embed:tomcat-embed-el:${tomcatVersion}"
      }
    }
```

**Comment by johndevs** [comment]
The vaadin-*  configurations comes with a resolution strategy predefined (https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/fi/jasoft/plugin/GradleVaadinPlugin.groovy#L524) which will set the correct vaadin versions if wrong ones are inherited as well as do those necessary overrides to avoid version conflicts. 

If you are overriding the resolution strategies then you will need to handle the version conflicts yourself. I think you can just copy over what the plugin does into your resolutionStrategy and it should work.
