### ISSUE TITLE
Tried to run task listener on non-applicable project xxx

### ISSUE THREAD

**Issue by ar** [johndevs/gradle-vaadin-plugin#327]
In the latest release `1.1.2` I started to see a new warning on a multi-module project that uses Gradle Vaadin Plugin (warning is not raised up to version 1.1.1)

```
Tried to run task listener on non-applicable project XXX
...
Tried to run task listener on non-applicable project YYY
...
```

I see the change was probably introduced in c5fa5ab0 circa line 51:

```
   if ( !isApplicable(task) ) {
          task.project.logger.warn("Tried to run task listener on non-applicable project $task.project.name")
              return
    }
```

Is there a way for other modules on a system that do not require the Vaadin plugin to get around this warning?

**Comment by johndevs** [comment]
The log level for that log statement seems to be too high. The TaskExecutionListener will always run on all modules as it is attached to Gradle's Task Execution Graph that consists of all the modules in the build. 

So, please ignore that warning for now, I'll reduce the log level or remove the logging in the next maintenance version.
