### ISSUE TITLE
groovyProject is false by default

### ISSUE THREAD

**Issue by touitou** [johndevs/gradle-vaadin-plugin#345]
Hi,
When I see the project creator, GroovyProject is fault and there is no way to change it. It would be very usefull to be able to create groovyVaadin projects.
May you had a parameter to leave the choice to the developper?
Thanks

**Comment by touitou** [comment]
MeanWhile I could do this trhough Gradle by adding 2 tasks

task vaadinGroovyProject(type: Copy, dependsOn: 'vaadinCreateProject') {

    from 'src'
    into 'src'
    // Use a closure to map the file name
    rename { String fileName ->
        fileName.replace('.java', '.groovy')
    }
    ant.replace(dir: 'src', token: ';', value: "")
}

task graadinCreate(type: Delete, dependsOn: 'vaadinGroovyProject') {
    delete fileTree('src') {
        include '**/*.java'
    }
}

**Comment by johndevs** [comment]
Hi,

In a groovy project you should use the groovy plugin instead of the java plugin to get the correct source folders etc. You can do it by using the following in your build.gradle:
```
plugins {
    id 'fi.jasoft.plugin.vaadin.groovy' version '1.1.6'
}
```

**Comment by touitou** [comment]
Hi John,
that's what I do:
dependencies {
        //classpath 'org.akhikhl.gretty:gretty:+'
        classpath "fi.jasoft.plugin:gradle-vaadin-plugin:1.1.6"


    }
apply plugin: "fi.jasoft.plugin.vaadin.groovy"

But it still generates java files.

Thanks

**Comment by touitou** [comment]
PS: I work behind an enterprise network that's why I use dependencies to import the plugin form our enterprise repo
