### ISSUE TITLE
groovy Project

### ISSUE THREAD

**Issue by touitou** [johndevs/gradle-vaadin-plugin#346]
Sorry John,
I recreate an issue to be sure you don't miss my issue

Here is my build.gradle plugin apply code

plugins {
    id 'fi.jasoft.plugin.vaadin.groovy' version '1.1.6'
}

I launch the following  command
gradle vaadinCreateProject

It generates Java files. Is there a taks to generate Groovy project?

Thanks for your help much appreciated

**Comment by touitou** [comment]
Ok, so
I did some test with previous plugin  ersion and I had to go back to gradle 3.2.



With this build.gradle, groovy source Files are generated
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }

    }


}

plugins {
    id 'fi.jasoft.plugin.vaadin.groovy' version '0.11'
}

targetCompatibility = "1.8"


But with this one  (only the plugin version changed), it did not work
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }

    }


}

plugins {
    id 'fi.jasoft.plugin.vaadin.groovy' version '1.1.6'
}

targetCompatibility = "1.8"

**Comment by johndevs** [comment]
Hi, thanks for the clarification! Indeed it broken at some point. I'll fix it for the next maintenance release (``1.1.7``)

**Comment by touitou** [comment]
My pleasure. Thank you for your work, you plugin is awesome!
