### ISSUE TITLE
Exemple Project

### ISSUE THREAD

**Issue by jamroks** [johndevs/gradle-vaadin-plugin#35]
Hi John,

 I think it would be nice to have a compagion project for the plugin, just to illustrate the usage of this plugin . It will allow new comer to quickly get up and going  with new project . 

What do think about this ? 

By the way it seems that you used to have such project ? 

cheers

**Comment by zhuravskiy** [comment]
Hi jamroks, I fork CssInject plugin and migrate it from ivy to gradle, you can see it https://github.com/zhuravskiy/CSSInject 
Also i created template project for vaadin addon https://github.com/zhuravskiy/vaadin-addon-template, that i copy, change example strings, and fix head lines in build.gradle, a little code, and new vaadin addon is born :)

**Comment by livotov** [comment]
@jamroks you can also take a look at my webapp skeleton I recently created as a simple bootstrap for new projects. It contains vaadin web module (using this plugin) with custom theme as well as other modules and external dependencies 

https://github.com/LivotovLabs/WebApplicationSkeleton

**Comment by johndevs** [comment]
Added a new wiki to this gradle repository to gather information in. It can be found at https://github.com/johndevs/gradle-vaadin-plugin/wiki
