### ISSUE TITLE
Cannot use gradle-vaadin-plugin with gretty

### ISSUE THREAD

**Issue by valkolaci** [johndevs/gradle-vaadin-plugin#353]
If I try to combine gretty & gradle-vaadin-plugin in a single project, it fails. Using only one of them is okay.

Using this build.gradle:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.akhikhl.gretty:gretty:+'
    }
}

plugins {
    id "fi.jasoft.plugin.vaadin" version "1.1.6"
}

group 'whatever'
version '1.0-SNAPSHOT'

repositories {
    jcenter()
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'war'
apply plugin: 'org.akhikhl.gretty'
```
gives this error message:

> Error:Cannot change dependencies of configuration ':providedCompile' after it has been included in dependency resolution.

Moving the plugins section to the front
```
plugins {
    id "fi.jasoft.plugin.vaadin" version "1.1.6"
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.akhikhl.gretty:gretty:+'
    }
}

group 'whatever'
version '1.0-SNAPSHOT'

repositories {
    jcenter()
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'war'
apply plugin: 'org.akhikhl.gretty'
```
gives this error message:

> Error:(6, 0) Cause: startup failed:
> build file 'whatever/build.gradle': 6: all buildscript {} blocks must appear before any plugins {} blocks in the script
> 
> See https://docs.gradle.org/3.4.1/userguide/plugins.html#sec:plugins_block for information on the plugins {} block
> 
>  @ line 6, column 1.
>    buildscript {
>    ^

**Comment by johndevs** [comment]
The vaadin plugin comes with a run task you can use without Gretty, just run **vaadinRun** to run the project.

But, if you want to use multiple plugins you should use:
```
plugins {
  id "org.akhikhl.gretty" version "1.4.2"
  id "fi.jasoft.plugin.vaadin" version "1.1.6"
}
```
