### ISSUE TITLE
No compile on multi theme

### ISSUE THREAD

**Issue by aluismarte** [johndevs/gradle-vaadin-plugin#354]
Cant compile when have 2 or more folder with diferent themes.

MyTheme
Test

Failed to find src/main/webapp/VAADIN/themes/Test/styles.scss pre-compiled styles.css file.

Plugin 1.1.7 on Spring Boot Gradle

Test all version and work good t init to 1.1.2, on 1.1.3 fail to 1.1.7

**Comment by johndevs** [comment]
Do you have a *styles.scss* file in Test?

**Comment by aluismarte** [comment]
Look

![screenshot from 2017-04-03 14-23-48](https://cloud.githubusercontent.com/assets/2516303/24624278/478de9bc-1879-11e7-9029-8a9424109ebb.png)

**Comment by johndevs** [comment]
Might be related to #363

**Comment by johndevs** [comment]
@aluismarte Could you try again with ``1.1.8``?

**Comment by aluismarte** [comment]
Always get this when i compile my theme, but i get my style.css normal and working on version 1.1.2

com.vaadin.sass.internal.parser.ParseException: Argument substitution error: there is no value for the argument duration. Formal arguments: FormalArgumentList[$name: null, $duration: null, $easing: null], actual arguments: Actual argument list [ArgumentList [valo-animate-out-fade 120ms]] at line -1, column -1
com.vaadin.sass.internal.parser.ParseException: Argument substitution error: there is no value for the argument duration. Formal arguments: FormalArgumentList[$name: null, $duration: null, $easing: null], actual arguments: Actual argument list [ArgumentList [valo-overlay-animate-in 120ms]] at line -1, column -1
com.vaadin.sass.internal.parser.ParseException: Argument substitution error: there is no value for the argument duration. Formal arguments: FormalArgumentList[$name: null, $duration: null, $easing: null], actual arguments: Actual argument list [ArgumentList [valo-animate-out-fade 120ms]] at line -1, column -1
vaadinThemeCompile FAILED

If you see is vaadin valo, but on version less and equal to 1.1.2 compile and get work

This my conf con styles.scss

@import "test";

@include test;

**Comment by johndevs** [comment]
That means that you are using some construct in your SASS theme that is not compatible with the Vaadin Sass compiler. Are you using the latest Vaadin version with and are you manually setting valo-animate-out-fade somewhere in your theme maybe?

You need to get rid of that ParseException before the theme can compile, this does not really have to do with the plugin at all. 

If you can't get it to work, copy your theme outside of the project, create a new theme with ``vaadinCreateTheme --name=<name-of-theme>`` and copy your old theme back piece by piece until you find the error.
