### ISSUE TITLE
Please add the "fetch" mode along with the CDN mode

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#355]
Hi John, would it be possible to add support for "fetch" along with the support for CDN? Using "fetch" instead of "CDN" will allow you to run the app even if Vaadin CDN is down. Thanks!

**Comment by johndevs** [comment]
Yes, that would be a nice feature!

https://vaadin.com/blog/-/blogs/demystifying-widget-set-cloud-compilation

**Comment by johndevs** [comment]
Now that I read through what fetch mode is then to me it sounds that the Gradle Vaadin Plugin already does it by default. The current behavior is to download the widgetset and put it in the project at build time. No extra flag is needed.

The "CDN" mode is not really supported and the question is that should the plugin even support it as it is not really optimal to always download the widgetset every time the application runs.

**Comment by johndevs** [comment]
Closing this as I don't see anything new to be added.
