### ISSUE TITLE
When manageDependencies is true, please add support for using the Vaadin8 compatibility package

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#356]
By default then `manageDependencies` is true, Gradle-vaadin-plugin only adds `vaadin-server` and `vaadin-client-compiled` (or `vaadin-client`) onto the classpath. Yet, Vaadin 8 introduced the compatibility packages in separate jar files.

Please, could you add support for also adding the `vaadin-compatibility-server` and `vaadin-compatibility-client` on classpath if appropriate gradle-vaadin-plugin configuration option is turned on? Thanks :)

**Comment by johndevs** [comment]
The compatibility jars are meant as a temporary measure so I don't think the plugin should support them with an option. The option would not make sense for Vaadin 7 or Vaadin 9 projects.

But, nothing prevents you to add them manually with:
```
dependencies {
    compile 'com.vaadin:vaadin-compatibility-server:8.+'
    compile 'com.vaadin:vaadin-compatibility-client:8.+'
}
```
When the compatibility jars are added the plugin will automatically detect them and adjust for example to use the compatiblity widgetset.
```

**Comment by mvysny** [comment]
Thanks, that's true. Just for the record, it's better to use `providedCompile` like this:
```
dependencies {
    compile "com.vaadin:vaadin-compatibility-server:${vaadin.version}"
    providedCompile("com.vaadin:vaadin-compatibility-client:${vaadin.version}") {
        // https://www.gesellix.net/post/providedcompile-and-compile-dependencies-with-gradle/
        transitive = false
    }
}
```
This way, the `gwt-user.jar` and `vaadin-compatibility-client.jar` won't be packaged needlessly into the WAR file.
