### ISSUE TITLE
GroovyCastException in Util.groovy

### ISSUE THREAD

**Issue by oflege** [johndevs/gradle-vaadin-plugin#358]
Commit dd3a15dc (Fix codenarc issues) introduced a bug in Util.groovy, Lines 586 and 603:
`File webAppDir = project.vaadinCompile.outputDirectory ?: ...`

The problem is that vaadinCompile.outputDirectory is a String, not a File (as the rhs of the ?: is)
Since new File(a,b) accepts both a String or a File as first parameter, the previously used `def webAppDir = ...` was ok, the current version runs into a GroovyCastException if vaadinCompile.outputDirectory is defined

**Comment by johndevs** [comment]
Thanks, you are absolutely right! This will be fixed in the next maintenance release.
