### ISSUE TITLE
BuildClassPathJar task and multi-module build

### ISSUE THREAD

**Issue by gwyn** [johndevs/gradle-vaadin-plugin#360]
The BuildClassPathJar task does not pick up artifacts from sub-projects on the first run. It only includes compile dependencies that exist when the evaluation phase of Gradle is complete.

The culprit is the isFile() check in line 49:
```
CompositeFileCollection files = (serverConf + classPath).filter { File file ->
file.isFile() && file.name.endsWith('.jar')
```

On the next run (without a clean), the artifacts have been built already and are picked up correctly.

I tried to get the manifest created at task execution, but failed. Maybe there is a better way, but for now I simply removed the isFile() check as a quick workaround.

I ran into this problem, because in my setup a subproject of the Vaadin project contains themes with SCSS files. The main theme in the Vaadin project references the subproject's theme.

**Comment by johndevs** [comment]
The isFile() was added there to ensure that no directories ending with .jar would be included. This is however very unlikely and even if they were included it wouldn't matter. So I think it would be safe to remove that check.
