### ISSUE TITLE
Theme Compilation when theme is in non-default root directory

### ISSUE THREAD

**Issue by fronk32** [johndevs/gradle-vaadin-plugin#363]
We're attempting to update to v1.1.6 and am having issues with theme compilation. We have a non-default root directory defined for themes using vaadinThemeCompile.themesDirectory. Attempting to compile the theme results in empty .scss files, corrupted images and the Vaadin themes being pulled into the root theme directory.
If I move our theme to the default directory (src/main/webapp/VAADIN/themes), the theme compiles as expected.
The issue appears to have been introduced in v1.1.3, compiling themes in non-default root directories works in prior versions.

**Comment by lkrasnov** [comment]
I am experiencing this exact same issue with gradle plugin v1.1.6 and vaadin 8.0.5

**Comment by johndevs** [comment]
Could you run the gradle build with the ``--info`` flag and paste the output? 

Also if you can paste the vaadin parts of your ``build.gradle`` file it would be helpful to be able to reproduce the issue.

**Comment by johndevs** [comment]
Found a couple bugs when using the the ``libsass`` compiler and a custom directory. Will fix that along with this ticket. For now if you are using a custom theme directory the workaround is to use the vaadin sass compiler until the next maintenance version.

**Comment by lkrasnov** [comment]
[https://gist.github.com/lkrasnov/5dcc4dc0778e258d69825f749ce0ac22](Output from running vaadinThemeCompile task )

I am specifying the theme compiler in the configuration, so I should be using the vaadin compiler by default. My workaround has been to switch to version 1.1.2 of the plugin.

`plugins {
	id 'fi.jasoft.plugin.vaadin' version '1.1.6'
}

vaadin {
	version '8.0.5'

	vaadinThemeCompile {
		themesDirectory 'src/main/resources/VAADIN/themes'
		compress false
	}
}`
