### ISSUE TITLE
VaadinRun doesn't generate themes?

### ISSUE THREAD

**Issue by leppaott** [johndevs/gradle-vaadin-plugin#367]
I had a friend of mine clone a repo of mine and ran vaadinRun on it just to get a 404 on the page.
I told him to ran: 
> gradle vaadinCreateTheme --name mytheme

And everything was working properly as expected. Could vaadinRun include this behaviour in the future? 

Console showed
> No themes were found in themes directory directory '...webapp/VAADIN/themes', skipping theme compiler dependencies

And I used annotation @Theme("mytheme") in the project.

Thanks!

**Comment by johndevs** [comment]
``vaadinRun`` should just run the project, its not meant for generating anything. If ``vaadinRun`` would generate a theme for you then you would get a new theme every time you run the project.

When you create a project you should use ``vaadinCreateProject``, that will create all the necessery things like the theme, a UI annotated with the correct annotations like ``@Theme`` etc.
