### ISSUE TITLE
Getting Server process terminated with exit code 143. See jetty.log for further details.

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#368]
I'm using the 1.1.8 plugin and trying to run my project with the `vaadinRun` task, with the following configuration:
```
vaadin {
    version '8.0.5'
    logToConsole = true
    vaadinRun {
        server = 'jetty'
    }
}
```

Yet, for some reason the JVM dies out of nowhere, with the following error message: `Server process terminated with exit code 143. See jetty.log for further details.`.

1. There is no `jetty.log` file anywhere on my machine. Please modify the error message to print the full path to the jetty.log file instead.
2. I am using ProcessBuilder (commons-exec) to run sub-process (simple scripts) - could it be possible that after those scripts finish running, Gradle will kill the JVM with my server?
3. Is it possible to debug this thing?

**Comment by mvysny** [comment]
I have found out that `log.error("foo")` will kill the JVM for reasons that are beyond me. I am not able to debug the Jetty process in Intellij (since it's probably a subprocess of Gradle launched by Vaadin-Gradle-Plugin) - Intellij won't stop at breakpoints so I can't even find out what's going on. For the time being I will avoid using `vaadinRun` for development purposes.

**Comment by mvysny** [comment]
Further testing: 
1. System.err.println("foo") will correctly print foo and will not kill JVM.
2. System.out.println("foo") prints nothing and will not kill JVM.

Also slf4j complains that
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/mavi/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.12/42db62298b899818ff17352cbc00050e940bbfb0/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/mavi/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.8/e54f49a227611976642f81cf2106b81c1ece8bf5/logback-classic-1.1.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```
Yet I don't have slf4j-simple on my classpath nor in my Gradle dependencies. Maybe it's hooking into Jetty's logger under the hood, raising all sorts of havoc?

**Comment by johndevs** [comment]
> 1. System.err.println("foo") will correctly print foo and will not kill JVM.

So, no problem then(?).

>  2. System.out.println("foo") prints nothing and will not kill JVM. Filed as #369

Already closed #369 as it works as expected. Check my answer there to get the sysout print-outs.

> Also slf4j complains that ``Class path contains multiple SLF4J bindings.``

I'm not seeing that by default, no logging framework is added by default. Maybe some of your dependencies are pulling in the the logging frameworks? You can check your dependency hierarchy and exclude where necessary.

> 3. Is it possible to debug this thing?

You can attach a remote debugger. A very old video how to do it (https://youtu.be/opjN3xlQ9Xk?t=1m39s) but most is still valid (except the devmode thing).

**Comment by mvysny** [comment]
Regarding the slf4j: created a bug rgd this: #371

Regarding the original bug report: "process terminated with exit code 143": attached a simple project which demonstrates this immediate java process kill. Could you please check whether this is happening on your machine as well?
[vaadingradletest.zip](https://github.com/johndevs/gradle-vaadin-plugin/files/915572/vaadingradletest.zip)

**Comment by mvysny** [comment]
Updating to Vaadin Gradle plugin 1.1.9 will even terminate JVM immediately, without any slf4j logging:
```
./gradlew vaadinRun
:compileJava
:vaadinUpdateWidgetset SKIPPED
:processResources NO-SOURCE
:classes
:vaadinClassPathJar SKIPPED
:vaadinCompile UP-TO-DATE
:vaadinUpdateAddonStyles UP-TO-DATE
:vaadinThemeCompile UP-TO-DATE
:vaadinThemeCompress UP-TO-DATE
:vaadinRun
SLF4J: The requested version 1.7.16 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
Apr 24, 2017 12:34:54 PM fi.jasoft.plugin.JettyServerRunner$1 lifeCycleStarting
INFO: Jetty starting
Server process terminated with exit code 143. See jetty.log for further details.

BUILD SUCCESSFUL

Total time: 1.647 secs
```
I'll post a link to the project shortly.

**Comment by mvysny** [comment]
https://gitlab.com/vyzivus/simple-vaadin-gradle-app
Tag: vaadin-gradle-bug-368
