### ISSUE TITLE
TestBenchConfiguration cast exception

### ISSUE THREAD

**Issue by atistrcsn** [johndevs/gradle-vaadin-plugin#384]
Hi! 

I have updated to ver. 1.1.10 and I have the following error (with stacktracing ON):

```
:testClasses UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Cannot cast object 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated@6d31cb64' with class 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated@6d31cb64' with class 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'
	at fi.jasoft.plugin.TaskListener.configureTest(TaskListener.groovy:235)
	at fi.jasoft.plugin.TaskListener.beforeExecute(TaskListener.groovy:70)
...
```

**Comment by johndevs** [comment]
I think this is the same as #343.

Could you post the vaadin related parts of your build.gradle? Is your project a single or multimodule project?If you run ``gradle clean test`` does it work then?

**Comment by atistrcsn** [comment]
Ofc.

This is a multi-module build:
* main module
* \_ app module
* \_widgetSet module

I'm trying to run only the clean&build tasks of widgetSet module when the error occures.
`gradle clean test` is fine btw.

Vaadin ver.: 8.0.5
Gradle ver.: 3.5

**widgetSet build.gradle:**
Somehow the MD parser don't format my code I pasted here, so here is the gist:
[https://gist.github.com/atistrcsn/99b7aeae7d88f49d42ff627c81afa0d8](https://gist.github.com/atistrcsn/99b7aeae7d88f49d42ff627c81afa0d8)

**Comment by atistrcsn** [comment]
I can make code inserting to work (github newbie =)):

```gradle
plugins {
    id 'fi.jasoft.plugin.vaadin' version '1.1.9'
}

apply plugin: 'java'
description = '***-widgetset'

vaadinCompile {
    widgetset '***.AdminWidgetSet'
    widgetsetGenerator '***.admin.app.WidgetSetGenerator'
    userAgent "safari"
}

jar.dependsOn 'vaadinCompile'
jar.from 'src/main/webapp'
war.enabled false

configurations {
    justJar
}

artifacts {
    justJar jar
}

dependencies {
    compile group: 'com.vaadin', name: 'vaadin-context-menu', version: '2.0.0'
//    compile group: 'com.vaadin', name: 'vaadin-charts-compatibility', version: '4.0.0'
    compile group: 'org.vaadin.addons', name: 'vaadin-sliderpanel', version: '2.0.0'
    compile group: 'org.vaadin.addon', name: 'confirmdialog', version: '3.1.1'
    compile group: 'org.vaadin.addon', name: 'easyuploads', version: '8.0.0'
    compile group: 'org.vaadin.addons', name: 'vaadin-jcrop', version: '1.1.2'
    compile group: 'org.vaadin.addons', name: 'dom', version: '0.1.0'
    compile group: 'org.vaadin', name: 'viritin', version: '2.0.beta1'
    compile(group: 'com.vaadin', name: 'vaadin-compatibility-client', version: '8.0.5')
    compile(group: 'com.vaadin', name: 'vaadin-client-compiler', version: '8.0.5')
}
```

**Comment by atistrcsn** [comment]
UPDATED: `gradle clean test` has the same exception.

**Comment by johndevs** [comment]
Do you have a ``settings.gradle``? Do you have any Vaadin related there?

**Comment by atistrcsn** [comment]
Nothing vaadin related, only project names..
	





On Tue, May 2, 2017 at 7:15 PM +0200, "John Ahlroos" <notifications@github.com> wrote:












Do you have a settings.gradle? Do you have any Vaadin related there?

**Comment by johndevs** [comment]
Hi,

Could you try the new 1.2.beta1 version (https://plugins.gradle.org/plugin/com.devsoap.plugin.vaadin)?

A lot a of code around this has been improved and this shouldn't be an issue anymore.

**Comment by atistrcsn** [comment]
Hi,

I could try it, but right now I have no extra time for this. I will try it within 1-2 weeks. We have to provide some working demo to the client :)

**Comment by johndevs** [comment]
Alright, I'll close this then for now. Please re-open if you are getting something similiar with 1.2.x.

Good luck with the demo! :)

**Comment by dmmax** [comment]
Hi,

I have some problem and on new version: "com.devsoap.plugin:gradle-vaadin-plugin:1.2.1"

> Cannot cast object 'task ':kpsplus-vaadin-theme:vaadinCompile'' with class 'com.devsoap.plugin.tasks.CompileWidgetsetTask_Decorated' to class 'com.devsoap.plugin.tasks.CompileWidgetsetTask'
