### ISSUE TITLE
Code Server Port

### ISSUE THREAD

**Issue by JamesDrummond** [johndevs/gradle-vaadin-plugin#392]
Code Server port is hardcoded to `9876`. There should be a way to configure this. https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/fi/jasoft/plugin/tasks/SuperDevModeTask.groovy#L94

**Comment by JamesDrummond** [comment]
Provided fix https://github.com/johndevs/gradle-vaadin-plugin/pull/393

**Comment by johndevs** [comment]
Hi, thanks for the fix. 

It looks like though the Vaadin Framework has the superdevmode code server port also hard-coded (https://github.com/vaadin/framework/blob/07d56a9ca050d976dec4f598ed39471ae369c588/client/src/main/java/com/vaadin/client/SuperDevMode.java#L188) so even if you could change it via the plugin  then it would break launching the app by using ?superdevmode in the URL. This could be confusing to users who would expect it would work.

**Comment by johndevs** [comment]
Fixed the issue with Vaadin where we also need to provide the url of the codeserver as a GET parameter.

Re-targeted the commits for 1.2 in PR #394

**Comment by johndevs** [comment]
Fix merged. Will be released with 1.2.

Thanks for the PR! :+1:

**Comment by JamesDrummond** [comment]
@johndevs Thanks. I am having trouble getting superdevmode java source code to show in Chrome browser. I have not worked with GWT or Vaadin in superdevmode before. Do you have any sort of walk through?

**Comment by AlexByte** [comment]
@JamesDrummond What is not clear? https://vaadin.com/docs/v8/framework/clientside/clientside-debugging.html
