### ISSUE TITLE
GET request not using gradle proxy settings

### ISSUE THREAD

**Issue by hillmich** [johndevs/gradle-vaadin-plugin#395]
When trying to run the `vaadinRun` task, it tries to access `https://plugins.gradle.org/plugin/fi.jasoft.plugin.vaadin` but does not honor the proxy settings, neither the system (env HTTP(S)_PROXY) nor the gradle.properties settings.

Below you the console output
```
$ ./gradlew -v

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.10.0-20-generic amd64

$ ./gradlew --debug --no-daemon vaadinRun
[...]
12:32:35.192 [QUIET] [org.gradle.api.Project] Using Gradle Vaadin Plugin 1.1.10
12:32:35.373 [DEBUG] [groovyx.net.http.HTTPBuilder] GET https://plugins.gradle.org/plugin/fi.jasoft.plugin.vaadin
12:32:35.433 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://plugins.gradle.org
12:32:35.470 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to plugins.gradle.org:443
12:32:56.476 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connect to plugins.gradle.org:443 timed out. Connection will be retried using another IP address
12:32:56.476 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to plugins.gradle.org:443
12:33:17.478 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connect to plugins.gradle.org:443 timed out. Connection will be retried using another IP address
12:33:17.478 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to plugins.gradle.org:443
12:33:38.482 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connect to plugins.gradle.org:443 timed out. Connection will be retried using another IP address
12:33:38.482 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to plugins.gradle.org:443
12:33:59.487 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connect to plugins.gradle.org:443 timed out. Connection will be retried using another IP address
12:33:59.487 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to plugins.gradle.org:443
12:34:20.481 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection org.apache.http.impl.conn.DefaultClientConnection@796c68bf closed
12:34:20.481 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection org.apache.http.impl.conn.DefaultClientConnection@796c68bf shut down
12:34:20.482 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@56d6a1b1
[...]
```

If I wait for long enough it will stop trying to connect and the build will eventually succeed. But this cannot be the expected behaviour.

Downloading other dependencies causes no problems and the log shows
```[DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 1][route: {tls}->PROXY:PORT->https://plugins.gradle.org:443][total kept alive: 2; route allocated: 1 of 20; total allocated: 3 of 20]```

I'm not quite sure this is caused by the plugin though.

**Comment by JoHeldmann** [comment]
Same problem here...

I think the problem is the usage of the class `HTTPBuilder` in `fi.jasoft.plugin.Util.getLatestReleaseVersion()`. 
`HTTPBuilder` doesn't use the Java proxy settings, it has its own `setProxy()` method.

Probably a slight modification (use `URL` instead of `HTTPBuilder`) in `getLatestReleaseVersion()` helps:

```groovy
    /**
     * Gets the latest released Gradle plugin version
     *
     * @return
     *      the latest released version number
     */
    @Memoized
    static VersionNumber getLatestReleaseVersion() {
        try {
            def html = new URL('https://plugins.gradle.org/plugin/fi.jasoft.plugin.vaadin').getText()
            def matcher = html =~ /Version (\S+)/
            if (matcher.find()) {
                return VersionNumber.parse(matcher.group(1))
            }
            VersionNumber.UNKNOWN
        } catch (IOException | URISyntaxException e){
            VersionNumber.UNKNOWN
        }
    }
```

BTW I would prefer this version check as an own task of the plugin and not being executed every time Gradle is called.

**Comment by christoph-frick** [comment]
If you switch over to `URL.getText()` also add timeouts; e.g. pass them as a map:

```groovy
url.getText([
	connectTimeout: 5000,
	readTimeout: 5000,
	useCaches: true,
	allowUserInteraction: false,
])
```

People have drop-policies for unconfigured proxies set (yes, it's braindead).

Also note, that `getText` does not work as well with redirects etc as a "proper" http client.

**Comment by johndevs** [comment]
Thanks for the suggestions!

I think we should go with HttpBuilder instead of URL as that is used in other places as well where the plugin does network requests. It is more robust in how it handles redirects etc as mentioned.

Moving the check into its own task and caching the results for some time is a good idea. It should allow you to easily disable the check by just ignoring the task and by caching the results it should reduce the amount of build delays when actively working with the code.

I'll release the change as part of the upcoming 1.2 release.
