### ISSUE TITLE
Support Gradle Kotlin DSL

### ISSUE THREAD

**Issue by napperley** [johndevs/gradle-vaadin-plugin#418]
Please add support for Gradle Kotlin DSL which is close to a stable release (currently at v0.9.1). Does the plugin use the current Gradle plugin APIs (action based ones)?

**Comment by johndevs** [comment]
The plugin should work fine with Kotlin DSL as far as I know. 

Is there something particular you are not able to do?

**Comment by napperley** [comment]
Both the old and new versions of the Gradle plugin work fine with the Gradle Kotlin DSL. Previously there was the issue of the new plugin not being found but that has since been resolved. Would be an excellent idea to **explicitly mention** that the plugin works with the Gradle Kotlin DSL in the documentation.
