### ISSUE TITLE
Missing Doc For Adding Plugin Repository

### ISSUE THREAD

**Issue by napperley** [johndevs/gradle-vaadin-plugin#419]
In the official plugin documentation there is no mention of adding a custom repository before applying the plugin. Where is the plugin repository located, and how can it be added using traditional **Gradle DSL**, or **Kotlin DSL**? At the moment the following errors occur in Gradle when running the **vaadinRun** task:

```
Error:Could not find com.devsoap.plugin.vaadin:gradle-vaadin-plugin:1.2.0.
Searched in the following locations:
    file:~/.gradle/caches/4.1-20170624053347+0000/embedded-kotlin-repo-1.1.3-1/repo/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.pom
    file:~/.gradle/caches/4.1-20170624053347+0000/embedded-kotlin-repo-1.1.3-1/repo/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.jar
    https://jcenter.bintray.com/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.pom
    https://jcenter.bintray.com/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.jar
    https://repo1.maven.org/maven2/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.pom
    https://repo1.maven.org/maven2/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.jar
    https://plugins.gradle.org/m2/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.pom
    https://plugins.gradle.org/m2/com/devsoap/plugin/vaadin/gradle-vaadin-plugin/1.2.0/gradle-vaadin-plugin-1.2.0.jar
Required by:
    project :
```

**Comment by napperley** [comment]
Below is a sample Gradle build file (**build.gradle.kts**) which works with the **old** version of the plugin:

```kotlin
import fi.jasoft.plugin.tasks.RunTask as VaadinRun

val KOTLIN_VER = "1.1.3-2"
val VAADIN_VER = "8.0.6"

group = "org.example"
version = "0.1-SNAPSHOT"

// Section for setting up plugin repositories and dependencies.
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        // Have to manually specify the version due to a Gradle Kotlin DSL bug.
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.3-2")
        // Have to manually specify the version due to a Gradle Kotlin DSL bug.
        classpath("fi.jasoft.plugin:gradle-vaadin-plugin:1.1.12")
//        classpath("com.devsoap.plugin.vaadin:gradle-vaadin-plugin:1.2.0")
    }
}

plugins {
    application
    kotlin("jvm")
}

apply {
    //    plugin("com.devsoap.plugin.vaadin")
    plugin("fi.jasoft.plugin.vaadin")
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib-jre8:$KOTLIN_VER")
    compile("org.jetbrains.kotlin:kotlin-runtime:$KOTLIN_VER")
}
```

**Comment by johndevs** [comment]
The version you are trying to use (1.2.0) does not exist yet. Try 1.2.0.beta5 :)

**Comment by napperley** [comment]
Unfortunately using *1.2.0.beta5* as the version doesn't work.

**Comment by napperley** [comment]
What is the full dependency notation for the plugin? Tried the following in
the *dependencies* block (inside the *buildscript* block) which doesn't
work: *classpath("com.devsoap.plugin.vaadin:gradle-vaadin-plugin:1.1.12")*.

**Comment by johndevs** [comment]
I'm sorry, I meant 1.2.0.beta1

**Comment by johndevs** [comment]
The easiest way to use the plugin is instead using the plugins{} block instead of using the buildscript block. 

You can follow the tutorials at https://github.com/johndevs/gradle-vaadin-plugin/wiki to get started.

And if you are making a kotlin projekt then you need to use the kotlin plugin. See https://github.com/johndevs/gradle-vaadin-plugin/wiki/Creating-a-Kotlin-Project

**Comment by napperley** [comment]
Is the "plugins" block for the traditional Gradle DSL, or Gradle Kotlin DSL?

**Comment by johndevs** [comment]
It is for both. 

https://kotlinlang.org/docs/reference/using-gradle.html

**Comment by napperley** [comment]
The Gradle documentation that is referred to is for the traditional Gradle DSL (the code examples are **NOT** the same, some are very similar though). Worked out how to do the same thing with the Kotlin DSL by doing the following:

```kotlin
plugins {
    // ...
    id("com.devsoap.plugin.vaadin").version("1.2.0.beta1")
}
```

In the Gradle documentation it mentions that the **plugins** API is currently experimental so it could break in any future Gradle version. Now able to use the new version of the Vaadin plugin :) . Would be very important to have a Gradle Kotlin DSL section in the documentation if possible.
