### ISSUE TITLE
vaadinCompile can't access temp directory on Windows, compilation failed

### ISSUE THREAD

**Issue by atistrcsn** [johndevs/gradle-vaadin-plugin#429]
Trying to vaadinCompile the widgetset, but the folowing error occurs every time. I am not sure it's really a ACL problem on my temp dir, or the GWT module has a bad manner.

Error log:
[gist of error.log](https://gist.github.com/atistrcsn/d0ac4b42272eb6b440ba7bdadbbbb89c)

JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Gradle ver: 4.0.1
Vaadin plug. ver.: 1.2.0.
Vaadin: 8.0.6

If I missed anything else, please let me know.

**Comment by johndevs** [comment]
This is a common ACL Windows problem it seems. The temp directory needs to be writable for Java to be able to write temp files to it. Looks like this is some kind of Windows 10 issue specifically...

You could follow the instructions on https://customer.real.com/hc/en-us/articles/204039863-Permission-to-write-to-TEMP-folder-and-Windows-system-folders to make the temp directory writable again or, alternatively, then you can change the "TEMP" system property to point to a directory that is writable.

This is more a system related issue the plugin can't do anything about really, you most likely will get the same when doing ``File.createTempFile(..)`` in any Java app, so closing this.

**Comment by atistrcsn** [comment]
Thanks for the fast response, I really appreciate it right now! I'll check it out and respond.
Keep up the good work ;-)

**Comment by atistrcsn** [comment]
So, I have set the -Djava.io.temdir to custom dir in the vaadinCompile configuration block and the compiler successfully worked. Altough, the vaadinThemeCompiler failed with the same Access denied exception with sasslib option enabled. 
Is there a way to pass jvmArgs to vaadinThemeCompile task the same way as vaadinCompile?

Exception message:
`Exception in thread "main" java.lang.ExceptionInInitializerError
at io.bit3.jsass.Compiler.<init>(Compiler.java:32)
at com.devsoap.plugin.LibSassCompiler.main(LibSassCompiler.java:54)
Caused by: io.bit3.jsass.adapter.LoaderException: java.nio.file.AccessDeniedException: C:\WINDOWS\libjsass-4190252637127087678
at io.bit3.jsass.adapter.NativeLoader.loadLibrary(NativeLoader.java:51)
at io.bit3.jsass.adapter.NativeAdapter.<clinit>(NativeAdapter.java:28)
... 2 more
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\libjsass-4190252637127087678
`

**Comment by christoph-frick** [comment]
@atistrcsn You could try this for your tasks (instead of `bootRun`):
```gradle
bootRun.systemProperties = System.properties // pass sysprops down to bootRun, so we can add them in configs in intellij
```

**Comment by atistrcsn** [comment]
@christoph-frick Good tip, thank you. The solution for me was the next:

`vaadinThemeCompile.compiler = 'libsass'
vaadinCompile {
    jvmArgs = ['-Xmx1512M', '-Xms512m', '**-Djava.io.tmpdir=${rootProject.buildDir}/temp**']
}

**tasks.withType(JavaExec) {
    // Assign all Java system properties from
    // the command line to the JavaExec task.
    systemProperties System.properties
}**`

**Comment by atistrcsn** [comment]
@johndevs Sorry, but IMHO something wrong with the libsass compiler default configuration. The compiler wants to write in a directory under the c:\windows directory, but AFAIK it's read only for all apps on Windows.  Isn't it?

The following error occured:

`Exception in thread "main" java.lang.ExceptionInInitializerError
at io.bit3.jsass.Compiler.<init>(Compiler.java:32)
at com.devsoap.plugin.LibSassCompiler.main(LibSassCompiler.java:54)
Caused by: io.bit3.jsass.adapter.LoaderException: java.nio.file.AccessDeniedException: C:\WINDOWS\libjsass-1895117388102727884
at io.bit3.jsass.adapter.NativeLoader.loadLibrary(NativeLoader.java:51)
at io.bit3.jsass.adapter.NativeAdapter.<clinit>(NativeAdapter.java:28)
... 2 more
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\libjsass-1895117388102727884
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)`

**Comment by johndevs** [comment]
@atistrcsn You need to make sure ``Files.createTempDirectory()`` works on your system. Many libraries use that so only working it around in the plugin will only postpone the problem. You can create a small test Java app with only that line in main() and ensure that runs on your system.

In this case it is the jsass compiler (the plugin depends on) which is trying to create a temp directory at https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/adapter/NativeLoader.java#L41 . The plugin can't change that as it is done in the constructor of the compiler, so the only solution is to get ``Files.createTempDirectory()`` working.

**Comment by atistrcsn** [comment]
@johndevs I understand the problem now. Thanks. I'll try to make java to write on WinNT filesystem.
I'll get back with the solution if I find it. It may be useful 4 someone.
