### ISSUE TITLE
Make plugin compatible with 3.5 versions of Gradle.

### ISSUE THREAD

**Issue by sdelamo** [johndevs/gradle-vaadin-plugin#430]
Plugin is currently only compatible with versions of Gradle 4.0 or higher. 

Unfortunately Gradle 4.0 contains numerous breaking changes: 

https://docs.gradle.org/current/release-notes.html#potential-breaking-changes

We are trying to use the Gradle Vaadin plugin in a [Grails 3](http://grails.org) application. Unfortunately, latest version of Grails only supports Gradle 3.5 due to the previously mentioned breaking changes in Gradle API.

Would it be possible to release this plugin with a lower Gradle compatibility requirement. For example, 3.5 would suffice. 

Thanks in advanced.

**Comment by johndevs** [comment]
Hi,

Unfortunately those exact breaking changes done by Gradle are the reason why the plugin cannot be backward compatible with Gradle 3.5.

But I'm sure the Grails project will update their support if we give them some time, Gradle 4.0 was just released. In the mean time I'm afraid you will have to continue using the 1.1.x.

**Comment by johndevs** [comment]
At least according to https://github.com/grails/grails-core/issues/10704 Gradle 4.0 should work with Grails 3.3.0+ so if you are using that version then it is probably a Grails issue you might get help with on the Grails forums.
