### ISSUE TITLE
Proper way to generate jar with complied widgets

### ISSUE THREAD

**Issue by endertunc** [johndevs/gradle-vaadin-plugin#432]
Hi all,

Related: https://github.com/johndevs/gradle-vaadin-plugin/issues/375#issuecomment-294532109

As discussed on the another issue I would like to find a suggested/preferred way to generate runnable jar using spring-boot&gradle-vaadin-plugin that contains compiled add-on widgets.

As far as I can see from the source code (https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/com/devsoap/plugin/actions/SpringBootAction.groovy#L51) `bootRun` creates the necessary widget files before running the server.

The problem here is that we can not get same behavior using the `bootRepackage`. Addon widgets aren't compiled and so they are not included into jar.

As of now, suggested way is working like this (the only place you can find is some closed issue's comment --not on the docs or wiki...);
```
jar {
    baseName = 'name'
    // Include app theme + compiled widget as well as classes into our jar
    from 'src/main/webapp', sourceSets.main.output
    // Compile theme and widgetset before creating jar
    dependsOn 'vaadinCompile', 'vaadinThemeCompile'
    // Sprinkle some spring boot sugar on the jar to make it runnable
    finalizedBy bootRepackage
}
```

Is this approach safe to use? Is it possible to make `bootRepackge` behave like `bootRun`.

**Comment by johndevs** [comment]
> Is this approach safe to use?

The approach is basically the same as what the plugin does (https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/com/devsoap/plugin/actions/SpringBootAction.groovy#L79) so it is safe to use, but should be unnecessary when using the plugin.

> Is it possible to make bootRepackge behave like bootRun.

Yes! This should be done, I'll fix it for the next maintenance version :)
