### ISSUE TITLE
Resources does not follow the SerlvetUrl&Resource Mapping

### ISSUE THREAD

**Issue by endertunc** [johndevs/gradle-vaadin-plugin#435]
Hi all,

I am having the following issue https://github.com/vaadin/spring/issues/227 and I think it might be related with gradle-vaadin-plugin.

When I change urlMapping ( /* -> /app) and resource mapping (/VAADIN/* -> /app/VAADIN/*) it couldn't find the static files and fails.

Best regards.
Ender

**Comment by johndevs** [comment]
This is more how Vaadin Framework works than how the plugin manages the project I think as also can be read from the comments in vaadin/spring#227.
