### ISSUE TITLE
Cannot cast object TestBenchConfiguration_Decorated to class TestBenchConfiguration

### ISSUE THREAD

**Issue by dmmax** [johndevs/gradle-vaadin-plugin#436]
Hello,

I have some problem same as issue:  https://github.com/johndevs/gradle-vaadin-plugin/issues/384

I have multimodule gradle project.

When I using 'classpath "fi.jasoft.plugin:gradle-vaadin-plugin:1.1.12' and I call script 'gradlew clean build', 
I get Error:
> Cannot cast object 'task ':vaadin-theme:vaadinCompile'' with class 'com.devsoap.plugin.tasks.CompileWidgetsetTask_Decorated' to class 'com.devsoap.plugin.tasks.CompileWidgetsetTask'

But command 'gradlew bootRun' (SpringBoot) running exactly.

When I using 'com.devsoap.plugin.vaadin' version '1.2.1', I get same error in 'gradlew clean build' and 'gradlew bootRun'.

For test, I create simple project but not multimodule,  I using 'com.devsoap.plugin.vaadin' version '1.2.1'. Commands 'bootRun' and 'build' work exactly. 

What should I do to make the multimodule project work?

P.S.: Sorry for my English.

**Comment by johndevs** [comment]
This issue is that you most likely have multiple different versions of the plugin in your build. Please check that all your submodules in the project are using the **exact** same version of the plugin.

**Comment by dmmax** [comment]
Yes..when I add plugin via 
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.devsoap.plugin:gradle-vaadin-plugin:1.2.1"
  }
}
```
not working, but when I add plugin via 
```
plugins {
    // Tell Gradle to add Vaadin support
    id 'com.devsoap.plugin.vaadin' version '1.2.1' apply false
   ...
}
```
sprintBoot and build work exactly

Thanks!

**Comment by johndevs** [comment]
Okay, good you got it solved. :+1:
