### ISSUE TITLE
Push deps not included in Springboot uberjar

### ISSUE THREAD

**Issue by christoph-frick** [johndevs/gradle-vaadin-plugin#445]
I have just [updated a project](https://github.com/christoph-frick/vdecl/commit/486123ae468037cdec2cfa1dc7e66c0f3f9010f9) to the 1.2 branch of the plugin and the deps for push are not part of the resuling uberjar (e.g. `./gradlew build` -> `build/libs/vdecl.jar` does not contain `vaadin-push-$V.jar` and its deps, resulting in the well known errors in starting up).

When running the project with `./gradlew bootRun`, the push works.

As a workaround I have for now added the libs as a `compile` dep manually.

Is this a TODO or an oversight with the recent changes to integrate Springboot better?  Or am I missing some toggle?  Ideally I would expect, that the resulting uberjar behaves more or less the same as a `bootRun` with the same config.

**Comment by johndevs** [comment]
I think it is a oversight, the push dependency should get included in the jar and work the same way as bootRun. I'll look into it for the next maintenance release.

**Comment by christoph-frick** [comment]
Awesome, thanks
