### ISSUE TITLE
Gradle Plugin 1.2.1/1.2.2 with spring boot don't clean/build without erros

### ISSUE THREAD

**Issue by Highstorm** [johndevs/gradle-vaadin-plugin#448]
Hi there,

i'm currently facing the issue that both, version 1.2.1 and the latest version 1.2.2 won't build or do any gradletask right now.

```
buildscript {
    ext {
        springBootVersion = '2.0.0.M3'
        springCloudVersion = 'Finchley.BUILD-SNAPSHOT'
    }
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {

        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

plugins {
    id "com.devsoap.plugin.vaadin" version "1.2.0"
    id 'war'
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
```

thats the gradle lines right now, and they work flawlessly.
if i update the version from 1.2.0 to 1.2.1 there is this error:

> Failed to apply plugin [id 'org.springframework.boot']
   > Cannot invoke method dependsOn() on null object

if i use 1.2.2 there is this error:

> > Could not resolve all files for configuration ':classpath'.
   > Could not find com.devsoap.plugin:gradle-vaadin-plugin:1.2.2.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.pom
         https://repo1.maven.org/maven2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.jar
         https://repo.spring.io/snapshot/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.pom
         https://repo.spring.io/snapshot/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.jar
         https://repo.spring.io/milestone/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.pom
         https://repo.spring.io/milestone/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.jar
         https://plugins.gradle.org/m2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.pom
         https://plugins.gradle.org/m2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.jar
     Required by:
         project :

did i miss something?

**Comment by christoph-frick** [comment]
I get the same error for 1.2.2 -- seems not to hit the mirrors yet.

**Comment by johndevs** [comment]
Reported to the Gradle bug tracker https://github.com/gradle/gradle/issues/2726

**Comment by livotov** [comment]
@johndevsjust tried sprint boot 2 and do see the same error when trying to use plugin 1.2.5 with sprint boot 2.0.0M6

> Failed to apply plugin [id 'org.springframework.boot']
> Cannot invoke method dependsOn() on null object

Is there any glue to fix this or plugin is not yet supposed to work with spring boot 2 ?
