### ISSUE TITLE
After upgrade to plugin 1.2.1, intellij errors out with 'configuration with name vaadin-server not found'

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#451]
I have created a bug in Intellij since I believe it's actually a bug in Intellij since the standard Gradle build succeeds: https://youtrack.jetbrains.com/issue/IDEA-177699
Yet, could this perhaps be also a bug on the gradle-vaadin-plugin's side?  It's easy to reproduce:

1. clone https://github.com/mvysny/karibu-helloworld-application
2. Import in intellij:

**Comment by mvysny** [comment]
![screenshot_20170821_125021](https://user-images.githubusercontent.com/254091/29513898-4edbe264-866f-11e7-8f38-f57ff2e800de.png)

**Comment by johndevs** [comment]
If you disable dependency management (in https://github.com/mvysny/karibu-helloworld-application/blob/26e11b9807b56c3ef91496cbe86f4ccbca9cbdd7/build.gradle#L11) then the plugin will not create the dependency configurations (vaadin-server). You will need to do it by hand in your own build.

**Comment by mvysny** [comment]
Thanks for the suggestion! I tried `configurations.create("vaadin-server")` but then intellij fails with `Error:(9, 0) Cannot add a configuration with name 'vaadin-server' as a configuration with that name already exists.`; when I remove that line, it reverts back to `Error:Configuration with name 'vaadin-server' not found.` :-D

Anyway, I don't depend on that `vaadin-server` configuration in my build, so it's being missed either by Gradle or the Intellij plugin (or something completely else)...

**Comment by johndevs** [comment]
The plugin does not officially support Gretty so you are pretty on your own if you want to use it currently with that project. Feel free to post the solution if you find it. 

My suggestion is to turn on dependency management so the plugin can include the correct dependencies. and configure the correct configurations.

**Comment by mvysny** [comment]
Tried to enable the managed dependencies and now it kinda works with Gretty 2.0.0 (only after the vaadin dependencies are also manually added to the `dependencies` block). I have to use Gretty because Vaadin Gradle Plugin Jetty integration is broken and doesn't print stdout unless --info is given: #369

**Comment by johndevs** [comment]
@mvysny Thanks for the thorough debugging messages, looks like Gradle 4 has changed a bit how dependency resolution is made.

**Comment by johndevs** [comment]
Gretty should work now with the latest release. I've made a PR for you at https://github.com/mvysny/karibu-helloworld-application/pull/1 to clean up and enable the new plugin ;)

**Comment by mvysny** [comment]
Awesome work, thanks John ;)
