### ISSUE TITLE
Jetty shows webapp directory instead of app using version 1.2.3

### ISSUE THREAD

**Issue by yissachar** [johndevs/gradle-vaadin-plugin#458]
Using the latest version `id 'com.devsoap.plugin:gradle-vaadin-plugin' version '1.2.3'`, when trying to access my application at `http://localhost:7070` Jetty instead just shows the contents of the webapp directory:

>Directory: /
>META-INF/ | 0 bytes | Jun 1, 2017 2:04:00 AM
>VAADIN/ | 0 bytes | Aug 27, 2017 1:04:45 PM
>WEB-INF/ | 4096 bytes | Jun 3, 2017 1:14:38 AM

In the previous version I was using ` id 'fi.jasoft.plugin.vaadin' version '1.1.12'`, this worked fine, and my application would be displayed. There are no startup errors or any indication that something went wrong, other than the fact that I can't access my app.

My config:

```
vaadin {
    version '7.7.7'
    useClassPathJar = false
    logToConsole = true
}

vaadinRun {
    server = 'jetty'
    serverPort = 7070
    openInBrowser = false
}
```

**Comment by johndevs** [comment]
Hi, tried to reproduce it by using your build gradle and creating a project with **vaadinCreateProject** and it seems to work and run ok. Maybe you could try to do the same and compare your project against a new one and see if there are any differences. There are no major differences between 1.1.12 and 1.2.3 regarding the jetty integration as far as I know.

**Comment by yissachar** [comment]
I did that and compared my project and noticed I had an empty `web.xml` in my project. I removed that and it started working again. It looks like the Jetty version changed between plugin versions, so presumably somewhere along the line Jetty changed how they handle blank `web.xml` files. Either way, I didn't need the file so it was a simple fix to remove it. 

Thanks!

**Comment by johndevs** [comment]
Good to hear :+1:
