### ISSUE TITLE
Add support for JVM hot reloading

### ISSUE THREAD

**Issue by yissachar** [johndevs/gradle-vaadin-plugin#460]
There is currently support for restarting the server when any changes are made, however this process can be slow since it requires a full stop-restart cycle. 

Using https://github.com/spring-projects/spring-loaded it should be possible to reload the changes on the running JVM without having to stop and restart the server.

**Comment by johndevs** [comment]
Good idea!

**Comment by yissachar** [comment]
Finally got a chance to test this out, and it rocks!  Thanks for being such an active and responsive maintainer 👍
