### ISSUE TITLE
upgrade from vaadin 7 to 8

### ISSUE THREAD

**Issue by thomaspp** [johndevs/gradle-vaadin-plugin#467]
Hello! I think I have a similar issue as #286 . I tried to uopdate from vaadin 7 to 8:

:vaadinCompileErrors in 'jar:file:/C:/Program%20Files/gradle-4.1/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/executable/ExecutableValidator.java' Line 53: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module? Line 94: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module? Tracing compile failure path for type 'javax.validation.ParameterNameProvider' Errors in 'jar:file:/C:/Program%20Files/gradle-4.1/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/ParameterNameProvider.java' Line 54: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module? Line 44: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module? Aborting compile due to errors in some input files

By forcing resolutionStrategy.force "javax.validation:validation-api:1.0.0.GA" I can complie but have during the runtime (starting the application) the problem, that the ParameterNameProvider is not available... Does anyone have an idea how the fix this? Thank you in advance!!

Build script:
`buildscript {
repositories {
maven { url "https://plugins.gradle.org/m2/" }
maven { url "http://oss.sonatype.org/content/repositories/vaadin-snapshots/" }
maven { url "http://maven.vaadin.com/vaadin-addons" }
}

dependencies {
    classpath("com.devsoap.plugin:gradle-vaadin-plugin:1.2.4")
    classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE")
}

}

apply plugin: 'war'
apply plugin: 'java'
apply plugin: 'eclipse-wtp'
apply plugin: 'org.springframework.boot'
apply plugin: 'com.devsoap.plugin.vaadin'

war {
baseName = test
version = '1.0'
manifest {
attributes("Implementation-Version": version)
}
}

vaadin {
version = '8.1.4'
}

vaadinCompile {
widgetset = 'TestWidgetset'
widgetsetGenerator = 'de.test.TestWidgetsetGenerator'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
compile("org.springframework.boot:spring-boot-starter")
compile("org.springframework.boot:spring-boot-starter-logging")
compile("org.springframework.boot:spring-boot-starter-data-jpa")
compile("org.springframework.boot:spring-boot-starter-web")
compile("org.springframework.boot:spring-boot-starter-mail")
compile("org.springframework.boot:spring-boot-starter-thymeleaf")
compile("org.springframework.boot:spring-boot-loader")

compile("org.mariadb.jdbc:mariadb-java-client:1.5.6")
compile("org.hsqldb:hsqldb:2.3.3")
compile("org.hibernate:hibernate-validator:6.0.2.Final")
compile("org.flywaydb:flyway-core:4.2.0")
compile("com.zaxxer:HikariCP:2.7.1") 

compile("org.apache.commons:commons-lang3:3.5")

compile("com.vaadin:vaadin-compatibility-server:8.1.4")
compile("com.vaadin:vaadin-compatibility-client:8.1.4") 
compile("com.vaadin:vaadin-compatibility-client-compiled:8.1.4") 
compile("com.vaadin:vaadin-compatibility-shared:8.1.4") 
compile("com.vaadin:vaadin-compatibility-themes:8.1.4") 
compile("com.vaadin:vaadin-bom:8.1.4") 
compile("com.vaadin:vaadin-push:8.1.4") 

compile("com.vaadin:vaadin-spring-boot-starter:2.0.1")
compile("org.vaadin.addons:vaadin-combobox-multiselect:2.0.1")
compile("org.vaadin.addons:vaadin-grid-util:2.1.0")
compile("org.vaadin.addons:fontawesomelabel:1.3.4")
compile("org.vaadin:viritin:2.0.beta2")

}

springBoot {
mainClass = "de.test.Application"
} `

**Comment by thomaspp** [comment]
Hello all! Does nobody have an idea how to fix this issue? Thanks in advance! Thomas

**Comment by johndevs** [comment]
Hi,

You could start by replacing your ``buildscript{}``-block and all your ``apply ...``'s with:

```groovy
plugins {
    id 'war'
    id 'eclipse-wtp'
    id 'org.springframework.boot' version '1.5.7.RELEASE'
    id 'com.devsoap.plugin.vaadin' version '1.2.4'
}
```
That will include and apply all your plugins in correct order.

Also, the Vaadin plugin will automatically add the Vaadin dependencies so you don't have to add them explicitly as compile dependencies. Equally the spring-boot dependencies will be added by the spring boot plugin so you won't need to add them explicitly either.

**Comment by thomaspp** [comment]
Hello! Thanks for the information, but I still have the issue that this wrong library is used:

-> javax.validation:validation-api:1.0.0.GA -> 1.1.0.Final

Any idea?

**Comment by johndevs** [comment]
Looks like your configuration exposed a bug that hadn't occurred before. It should get fixed in the next maintenance release.

**Comment by thomaspp** [comment]
Hello! Thanks for the fast answer. When do you release the next version? Regards, Thomas

**Comment by johndevs** [comment]
I'll put it out tomorrow, or at latest next weekend

**Comment by thomaspp** [comment]
Perfect, Thanks! :)
