### ISSUE TITLE
Additional GWT addon dependencies 

### ISSUE THREAD

**Issue by hansschtedke** [johndevs/gradle-vaadin-plugin#471]
Would be good to add an gradle option to name additional GWT dependencies explicit in addition to those marked with 'Vaadin-Widgetsets' in manifest file.

**Comment by johndevs** [comment]
Lets add this as an configuration option so to add a dependency to the compiler classpath you would add it as:
```
dependencies {
    vaadinCompile 'com.example:my-dependency:1.0'
}
```
It will be up to the developer to ensure that any transitive dependencies these dependencies have does not conflict with what the GWT compiler needs.

**Comment by hansschtedke** [comment]
Great!
