### ISSUE TITLE
Uncorrect dependencies location?

### ISSUE THREAD

**Issue by WLammert** [johndevs/gradle-vaadin-plugin#472]
Hello,

after following your tutorial from scratch I get a bunch of Exceptions mentioned below.

For research if followed the links that are mentioned in the exceptions, for example:
`Could not get resource 'https://repo1.maven.org/maven2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
`
It seems that https://repo1.maven.org/maven2/com/devsoap/  doesnt even exist in repository.

`Could not get resource 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.`
http://oss.sonatype.org/content/repositories/vaadin-snapshots/com/devsoap/ also doenst exist in repository.

`Could not get resource 'https://maven.vaadin.com/vaadin-prereleases/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom.`
https://maven.vaadin.com/vaadin-prereleases/com/devsoap/ also doenst exist in repository.

And so on.... Maybe you can give a hint if I missed something?

Here the Exceptions when I run **gradlew vaadinCreateProject**

`
> Configure project :
Using Gradle Vaadin Plugin 1.2.5

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AvalonGui'.
> Could not resolve all files for configuration ':vaadin-run-server'.
   > Could not resolve com.devsoap.plugin:gradle-vaadin-plugin:1.2.5.
     Required by:
         project :
      > Could not resolve com.devsoap.plugin:gradle-vaadin-plugin:1.2.5.
         > Could not get resource 'https://repo1.maven.org/maven2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
            > Could not HEAD 'https://repo1.maven.org/maven2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
               > Connect to repo1.maven.org:443 [repo1.maven.org/151.101.36.209] failed: Connection timed out: connect
      > Could not resolve com.devsoap.plugin:gradle-vaadin-plugin:1.2.5.
         > Could not get resource 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
            > Could not HEAD 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
               > Connect to oss.sonatype.org:443 [oss.sonatype.org/34.199.111.237, oss.sonatype.org/54.173.252.242, oss.sonatype.org/107.23.166.173] failed: Connection timed out: connect
      > Could not resolve com.devsoap.plugin:gradle-vaadin-plugin:1.2.5.
         > Could not get resource 'https://maven.vaadin.com/vaadin-prereleases/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
            > Could not HEAD 'https://maven.vaadin.com/vaadin-prereleases/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
               > Connect to maven.vaadin.com:443 [maven.vaadin.com/54.86.23.48] failed: Connection timed out: connect
      > Could not resolve com.devsoap.plugin:gradle-vaadin-plugin:1.2.5.
         > Could not get resource 'https://plugins.gradle.org/m2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
            > Could not HEAD 'https://plugins.gradle.org/m2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.5/gradle-vaadin-plugin-1.2.5.pom'.
               > Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.171.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.174.166, plugins.gradle.org/104.16.175.166] failed: Connection timed out: connect
   > Could not resolve fish.payara.extras:payara-embedded-web:4.1.153.
     Required by:
         project :
      > Could not resolve fish.payara.extras:payara-embedded-web:4.1.153.
         > Could not get resource 'https://repo1.maven.org/maven2/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
            > Could not HEAD 'https://repo1.maven.org/maven2/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
               > Connect to repo1.maven.org:443 [repo1.maven.org/151.101.36.209] failed: Connection timed out: connect
      > Could not resolve fish.payara.extras:payara-embedded-web:4.1.153.
         > Could not get resource 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
            > Could not HEAD 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
               > Connect to oss.sonatype.org:443 [oss.sonatype.org/34.199.111.237, oss.sonatype.org/54.173.252.242, oss.sonatype.org/107.23.166.173] failed: Connection timed out: connect
      > Could not resolve fish.payara.extras:payara-embedded-web:4.1.153.
         > Could not get resource 'https://maven.vaadin.com/vaadin-prereleases/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
            > Could not HEAD 'https://maven.vaadin.com/vaadin-prereleases/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
               > Connect to maven.vaadin.com:443 [maven.vaadin.com/54.86.23.48] failed: Connection timed out: connect
      > Could not resolve fish.payara.extras:payara-embedded-web:4.1.153.
         > Could not get resource 'https://plugins.gradle.org/m2/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
            > Could not HEAD 'https://plugins.gradle.org/m2/fish/payara/extras/payara-embedded-web/4.1.153/payara-embedded-web-4.1.153.pom'.
               > Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.171.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.174.166, plugins.gradle.org/104.16.175.166] failed: Connection timed out: connect
   > Could not resolve org.springframework:springloaded:1.2.8.RELEASE.
     Required by:
         project :
      > Could not resolve org.springframework:springloaded:1.2.8.RELEASE.
         > Could not get resource 'https://repo1.maven.org/maven2/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
               > Connect to repo1.maven.org:443 [repo1.maven.org/151.101.36.209] failed: Connection timed out: connect
      > Could not resolve org.springframework:springloaded:1.2.8.RELEASE.
         > Could not get resource 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
            > Could not GET 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
               > Connect to oss.sonatype.org:443 [oss.sonatype.org/34.199.111.237, oss.sonatype.org/54.173.252.242, oss.sonatype.org/107.23.166.173] failed: Connection timed out: connect
      > Could not resolve org.springframework:springloaded:1.2.8.RELEASE.
         > Could not get resource 'https://maven.vaadin.com/vaadin-prereleases/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
            > Could not GET 'https://maven.vaadin.com/vaadin-prereleases/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
               > Connect to maven.vaadin.com:443 [maven.vaadin.com/54.86.23.48] failed: Connection timed out: connect
      > Could not resolve org.springframework:springloaded:1.2.8.RELEASE.
         > Could not get resource 'https://plugins.gradle.org/m2/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/org/springframework/springloaded/1.2.8.RELEASE/springloaded-1.2.8.RELEASE.pom'.
               > Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.171.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.174.166, plugins.gradle.org/104.16.175.166] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
`

**Comment by johndevs** [comment]
Hi, 

the plugin is hosted in the Gradle plugin repository which is included by default by Gradle. 

> Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.171.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.174.166, plugins.gradle.org/104.16.175.166] failed: Connection timed out: connect

This indicates you are having problems connecting to it. Do you perhaps have any firewall blocking outbound connections to plugins.gradle.org? It could of course also be some temporary issue with their servers.
