### ISSUE TITLE
Any plans for Flow/Vaadin 10 support ?

### ISSUE THREAD

**Issue by deyaeddin** [johndevs/gradle-vaadin-plugin#473]

**Comment by christoph-frick** [comment]
In case you just want to fool around with it using Gradle, there is currently no need for a plugin.

**Comment by mvysny** [comment]
True. There is an example project here: https://github.com/mvysny/karibu10-helloworld-application

**Comment by christoph-frick** [comment]
If you are going for [webjars](https://github.com/vaadin/flow/blob/master/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc) you don't even need that.  Only dealing with version conflicts is needed.  E.g. https://github.com/christoph-frick/try-springboot-vaadin-flow/blob/master/build.gradle

**Comment by mvysny** [comment]
You're right - I've upgraded the https://github.com/mvysny/karibu10-helloworld-application to use webjars and now it works without any specialized plugin.

However there actually is the `maven flow plugin`: it's being used in the https://github.com/vaadin/skeleton-starter-flow project to transpile JS into es5 and es6.

**Comment by johndevs** [comment]
I don't think there will be any effort at least on my part to support  Vaadin Flow. The reason is that while it most likely could be done I think it would be better to do it in a separate plugin as the requirements are so different. That said, if somebody makes a nice pull request that integrates it with this plugin in a structurally good way then I will certainly help you get the pull request through.

**Comment by mvysny** [comment]
I assume that the flow plugin is actually really simple and only uses some command-line javascript tools to perform the transpilation. If this is true, perhaps this can be performed by a simple gradle-exec task and hence no other plugin would actually be necessary.

**Comment by johndevs** [comment]
I am closing this as ``wontfix`` as I'm happy to say there is now work being done on a separate plugin for vaadin 10 (flow). 

The plugin is located at https://github.com/devsoap/gradle-vaadin-flow and the first preview version that uses webjars will be released shortly. It is currently a work in progress and does not by a long shot have all the features this plugin has yet. It should for now be considered experimental.

The API of this plugin will in future versions move toward the API of the new plugin so in time it will be easy to transition from this to the new one when moving from Vaadin 8 to Vaadin 10.
