### ISSUE TITLE
Version 1.2.6 fails to find a widgetset

### ISSUE THREAD

**Issue by rsivan** [johndevs/gradle-vaadin-plugin#481]
I have a project which includes multiple plugin widgetsets.
It compiles OK under version 1.2.4 of this plugin, but when I try to build with 1.2.6 it breaks the build, as it cannot find a widgetset.

The displayed error is:
```
Unable to find 'com/vaadin/graph/GraphExplorerWidgetset.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rsivan/pv/trunk2/Src/VaadinClient/Pv3Widgetset/build.gradle' line: 145

* What went wrong:
Execution failed for task ':Src:VaadinClient:Pv3Widgetset:vaadinCompile'.
> Widgetset failed to compile. See error log.

```

**Comment by rsivan** [comment]
I think I figured this one out, I had to use vaadinCompile dependencies instead of plain compile.

**Comment by johndevs** [comment]
Good to hear :+1: I'll close this then.
