### ISSUE TITLE
Cyclic reference in VaadinServlet with vaadinCreateProject

### ISSUE THREAD

**Issue by Flamenco** [johndevs/gradle-vaadin-plugin#490]
I don't know if IJ is altering/formatting the file but I end up with a VaadinServlet that extends VaadinServlet.

<img width="614" alt="screen shot 2017-12-24 at 10 28 21 am" src="https://user-images.githubusercontent.com/819940/34327536-36112d06-e895-11e7-83a8-d6693da9e45b.png">

<img width="570" alt="screen shot 2017-12-24 at 10 27 50 am" src="https://user-images.githubusercontent.com/819940/34327533-20b03510-e895-11e7-8085-fd36372f1c46.png">

A workaround is to remove the import and explicitly use a FQN. 

I would recommend using MyVaadinServlet as the class name however.

**Comment by Flamenco** [comment]
I looked at the source code.  My project folder is named 'Vaadin' so that becomes the application name, and so it follows that the Servlet name is VaadinServlet.  See PR for possible solution.

**Comment by johndevs** [comment]
Fixed in b3a5ee723f7f9a49f08d6c306c0e417e7c8a7a66.
