### ISSUE TITLE
missing clean task?

### ISSUE THREAD

**Issue by nikkijuk** [johndevs/gradle-vaadin-plugin#495]
It could be useful to have task for cleaning project state (i.e. deleting build directory)-

I did copy previous version of my experiment as base to new experiment (whole root directory), and ended up to situation where I had compiled version of servlet in build directory and refactored servlet with different name in my project. It took some time to understand that "gradle vaadinRun" doesn't do any kind of cleanup but I need to manually delete "build" directory to get to clean state - otherwise old classes do pile up to "build" directory and might cause funny problems. 

I see how gradle-vaadin-plugin resembles to ng-cli and react-create-app and find it interesting to think it as "vaadin-cli". Thanks for providing this add on.

**Comment by christoph-frick** [comment]
Isnt that covered by the regular `clean` task from gradle?

**Comment by nikkijuk** [comment]
How silly from me. Yes. I guess there's no need for vaadin specific clean.
