### ISSUE TITLE
Add Run Code Server configuration

### ISSUE THREAD

**Issue by AlexByte** [johndevs/gradle-vaadin-plugin#502]
For SuperDevMode.

**Comment by johndevs** [comment]
You are probably looking for the Super Development Mode configuration that is used to run the code server. https://github.com/johndevs/gradle-vaadin-plugin/wiki/Tasks-and-configuration-DSL#vaadinsuperdevmode

**Comment by AlexByte** [comment]
This configuration is automatically terminated and you can not access http://localhost:9876
> Executing task 'vaadinSuperDevMode'...
> 
> Using Gradle Vaadin Plugin 1.1.6
> :compileJava
> :vaadinUpdateWidgetset
> :processResources UP-TO-DATE
> :classes
> :vaadinClassPathJar UP-TO-DATE
> :vaadinCompile UP-TO-DATE
> :vaadinSuperDevMode
> 
> BUILD SUCCESSFUL
> 
> Total time: 2 mins 16.686 secs
> 17:09:36: Task execution finished 'vaadinSuperDevMode'.

**Comment by johndevs** [comment]
Could you run the task with ``--info`` and post the output?
