### ISSUE TITLE
Deprecated property(Class) method is used

### ISSUE THREAD

**Issue by slovdahl** [johndevs/gradle-vaadin-plugin#503]
Using Gradle 4.6 and gradle-vaadin-plugin 1.3.1, I get the following warning:
```
The property(Class) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the ObjectFactory.property(Class) method instead.
        at build_6a12c5dmnq08kvd0jo9wwtrdi.run(/home/slovdahl/project/build.gradle:28)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

FWIW, line 28 in `build.gradle` is `apply plugin: 'com.devsoap.plugin.vaadin'`.

**Comment by johndevs** [comment]
Yes, we should fix this :+1:

**Comment by ar** [comment]
If it saves you a few seconds, problem seems to be in `at com.devsoap.plugin.GradleVaadinPlugin.apply(GradleVaadinPlugin.groovy:237)`

**Comment by johndevs** [comment]
To fix this it will require that we bump the minimum Gradle version required for building the project from 4.0 -> 4.3 where the replacement form ``PropertyState`` (``Property<T>``) was introduced.
