### ISSUE TITLE
Servlet JAR gets packed into WAR archive

### ISSUE THREAD

**Issue by sodevel** [johndevs/gradle-vaadin-plugin#508]
I am using Version 1.3.1 with Gradle 4.6 and Vaadin 7.7.13 and for some reason the Servlet JAR javax.servlet-api-3.1.0.jar gets packed into the WAR archive when i build my application. As far as i understand this does not belong there and also Tomcat is complaining about this (but runs the application).

This happens with a minimal Hello World application, the build file basically contains nothing but the plugin import and vaadin configuration.

**Comment by johndevs** [comment]
Sounds like a bug, the servlet API should not get deployed. But it should not cause any issues if it is either.
