### ISSUE TITLE
Build Fails with "could not find method mainSourceSet()"

### ISSUE THREAD

**Issue by rasifix** [johndevs/gradle-vaadin-plugin#509]
Could not find method mainSourceSet() for arguments [main Java source] on object of type com.devsoap.plugin.extensions.VaadinPluginExtension

gradle version: 4.6
plugin versions: 1.2.6 and 1.3.2

using example configuration from wiki

**Comment by rasifix** [comment]
I removed the following from the example config (wiki section 4)

    mainSourceSet sourceSets.main.java

then it works, at least for me. Either documentation broken or plug-in

**Comment by johndevs** [comment]
Fixed in Wiki
