### ISSUE TITLE
Could not find javax.validation:validation-api:null

### ISSUE THREAD

**Issue by rasifix** [johndevs/gradle-vaadin-plugin#510]
vaadinCompile fails with the above exception

 Could not find javax.validation:validation-api:null.
     Required by:
         project : > com.vaadin:vaadin-client:8.3.2 > com.google.gwt:gwt-elemental:2.8.2 > com.google.gwt:gwt-user:2.8.2

using Gradle 4.6 and gradle-vaadin-plugin 1.3.1

**Comment by christoph-frick** [comment]
Those versions work for me.  You might have to provide more information about what you are doing.

**Comment by rasifix** [comment]
buildscript {
	repositories {
		maven {
                     ...
		}
	}
	dependencies {
            ...
	    classpath "com.devsoap.plugin:gradle-vaadin-plugin:1.3.1"
	}
}

apply plugin: 'com.devsoap.plugin.vaadin'

vaadin {
	version '8.3.2' 
	manageDependencies true
	manageRepositories false
}

**Comment by rasifix** [comment]
The following hack fixed the problem... It looks like the gradle.properties with the corresponding versions is not found from the classpath.

```
def versionOverrides = [
    "javax.validation:validation-api": "1.0.0.GA",
    "javax.servlet:javax.servlet-api": "3.1.0",
    "fish.payara.extras:payara-embedded-web": "4.1.153",
    "org.springframework:springloaded": "1.2.8.RELEASE"
]

configurations.all {

        resolutionStrategy.eachDependency { DependencyResolveDetails details ->

            def overrideVersion = versionOverrides[details.requested.group + ":" + details.requested.name]

            if (overrideVersion != null && details.requested.version != overrideVersion) {
                logger.info "Overriding dependency ${details.requested.group}:${details.requested.name} version ${details.requested.version} --> $overrideVersion"
                details.useVersion overrideVersion
            }
        }
}
```

**Comment by johndevs** [comment]
Looks like you found a fix so closing this.
