### ISSUE TITLE
Support Vaadin 8.2+ and dependent vaadin-spring plugins

### ISSUE THREAD

**Issue by matthiasbasler** [johndevs/gradle-vaadin-plugin#518]
The current version 1.3.1 of the gradle-vaadin-plugin uses Vaadin 8.1 and the corresponding vaadin-spring (and similar) plugin dependencies. The library "vaadin-spring" is used in pre-release version "2.1.0.beta2" for which (seemingly) no sources exist in the maven repositories.

It would be nice if the plugin could use the latest Vaadin 8.2+ libraries and - as a result - choose the correct corresponding "vaadin-spring-boot-starter" (and "vaadin-spring-boot" and "vaadin-spring") versions. For Vaadin 8.2 and higher there exist real "release" versions of these plugins, not just beta versions.

At the moment I have tried following, but I am not sure this is a valid workaround (excerpt from build.gradle):
```
plugins {
	id 'io.spring.dependency-management' version 1.0.6.RELEASE
	id 'org.springframework.boot' //No version specified, see resolutionStrategy in settings.gradle
	id 'com.devsoap.plugin.vaadin' version '1.3.1'
	//1.3.1 by default uses Vaadin 8.1.8 (supports 8.1+) and vaadin-spring 2.1.0.beta2 (no sources)
}

// Dependencies_______________________________
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	//Needed? Seems to influence version(s) that's being used.
	implementation 'com.vaadin:vaadin-spring-boot-starter'
}

dependencyManagement {
    imports {
        mavenBom "com.vaadin:vaadin-bom:8.4.5"
    }
}

// Configuration______________________________
vaadin {
	version = '8.4.5' //Only use in conjunction with dependencyManagement{ } and mavenBom
}
```
This configuration uses Vaadin 8.45 and adds vaadin-spring-boot-starter 3.0.1 and dependencies to the classpath, but there is still a vaadin-spring-boot-starter 2.1.0.beta2 lingering in the classpath too, which worries me. It seems to work though and now I get sources downloaded for "vaadin-spring" & Co.

______
P.S. Just wondering: Is this plugin still under active development at all? Seems the focus is on vaadin 10 plugin now but vaadin 10 unfortunately doesn't work for me. (The demo projects don't show the grid widget in any of my browsers.)

**Comment by christoph-frick** [comment]
You mean "Vaadin 8.1" and not "Gradle 8.1"?

**Comment by johndevs** [comment]
Hi,

Indeed most of the focus right now is going to the flow plugin, at least until the first stable release of that plugin is made. 

Did you already try setting the starter version manually via
```
vaadinSpringBoot {
    starterVersion '3.0.1'
}
```
By default it is set to "2.+" which should probably be updated at some point.

**Comment by matthiasbasler** [comment]
> You mean "Vaadin 8.1" and not "Gradle 8.1"?

Of course, I will correct the mistake in my above text.

> Did you already try setting the starter version manually via ... starterVersion 

**Thanks a lot for this hint.** Using this property yields the expected classpath. It is exactly what I was hoping for. Except that I was searching for it in the wrong plugin.
