### ISSUE TITLE
problem download vaadin-themes

### ISSUE THREAD

**Issue by cristiangary** [johndevs/gradle-vaadin-plugin#530]
com.devsoap.plugin.vaadin : 1.4.0 
Problem trying to dowmload vaadin-themes . 
`Could not resolve all files for configuration ':vaadin-server'.
> Could not resolve com.vaadin:vaadin-themes:8.5.2}.
  Required by:
      project :
   > Could not resolve com.vaadin:vaadin-themes:8.5.2}.
      > Could not get resource 'http://10.5.5.244:8081/nexus/content/groups/public/com/vaadin/vaadin-themes/8.5.2%7D/vaadin-themes-8.5.2%7D.pom'.
         > Could not GET 'http://10.5.5.244:8081/nexus/content/groups/public/com/vaadin/vaadin-themes/8.5.2%7D/vaadin-themes-8.5.2%7D.pom'. Received status code 400 from server: Invalid repository path
   > Could not resolve com.vaadin:vaadin-themes:8.5.2}.
      > Could not get resource 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/vaadin-themes/8.5.2%7D/vaadin-themes-8.5.2%7D.pom'.
         > Could not GET 'http://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/vaadin-themes/8.5.2%7D/vaadin-themes-8.5.2%7D.pom'.
            > org.apache.http.client.ClientProtocolException (no error message)

`
**Typo in GradleVaadinPlugin line 347. double "}}"**

**Comment by johndevs** [comment]
Fixed by https://github.com/johndevs/gradle-vaadin-plugin/pull/529
