### ISSUE TITLE
Consider adding scala support

### ISSUE THREAD

**Issue by johndevs** [johndevs/gradle-vaadin-plugin#54]
Gradle supports Scala already through the Scala plugin (http://www.gradle.org/docs/current/userguide/scala_plugin.html).

Vaadin supports Scala through Scaladin (https://vaadin.com/directory#addon/scaladin) which hopefully soon will get Vaadin 7 support as well.

The gradle vaadin plugin could easily generate scala Vaadin application templates with a dedicated `createVaadinScalaProject` task as well as automatically include Scaladin as a dependency if the scala gradle plugin is used in the project.

**Comment by alexeyOnGitHub** [comment]
I have a multi-module project. I have to define this in top-level build.gradle 
```
    sourceSets.main.scala.srcDir "src/main/java"
    sourceSets.main.java.srcDirs = []
```
to be able to build both Java and Scala in the same project when Java code depends on Scala.
(as suggested here https://discuss.gradle.org/t/how-to-compile-a-java-class-that-depends-on-a-scala-class-in-gradle/6747 )

now, if I run "gradle build", I get 

> * What went wrong:
> Execution failed for task ':webui:vaadinUpdateWidgetset'.
> > No source sets was found.
> 

my env: 
vaadinVersion = '7.7.10'  // set in top-level build.gradle

and this is in my /webui/gradle.build file:

> buildscript {
>     repositories {
>         maven {
>             url "https://plugins.gradle.org/m2/"
>         }
>     }
>     dependencies {
>         classpath "com.devsoap.plugin:gradle-vaadin-plugin:1.2.0.beta1"
>     }
> }
> 
> apply plugin: 'war'
> apply plugin: "com.devsoap.plugin.vaadin"
> 

note - I used another (older)  plugin at first, which worked fine with Java (only):
> plugins {
>     id 'fi.jasoft.plugin.vaadin' version '1.1.11'
> }

now I'm trying to build this app with both Java+Scala and that plugin started failing, so I tried this newer one - com.devsoap.plugin.vaadin . but same error...

so, how can I use this plugin in a project 
* which has BOTH Java and Scala 
* AND where Java code depends on Scala
?

**Comment by alexeyOnGitHub** [comment]
solved this by adding this:
```
vaadin.mainSourceSet = sourceSets.main.allSource
vaadin {
    version = "$vaadinVersion"
}
```
