### ISSUE TITLE
Vaadin 14 with Gradle and npm

### ISSUE THREAD

**Issue by Aliziloubaf** [johndevs/gradle-vaadin-plugin#542]
We want to use the vaadin 14 but not working because of npm.
Our Projects setup and build is gradle and we could work with vaadin 13 with this setup.
Is there any Workaround, i can use?
Should i start the npm manuelly and if yes how?

**Comment by dawiemalan** [comment]
Switching compatibilityMode on will make it work like Vaadin 13. For example with Spring Boot, place this in your application.yml:

```
vaadin:
  compatibilityMode: true

```

**Comment by johndevs** [comment]
I think this is the wrong repository, I think this should be in https://github.com/devsoap/gradle-vaadin-flow instead. This plugin only supports Vaadin up to 8.
