### ISSUE TITLE
How run custom gradle task before vaadinCompile runs

### ISSUE THREAD

**Issue by myungsunscott** [johndevs/gradle-vaadin-plugin#545]
When running: `gradle build`, a series of tasks kick off. 

In my build.gradle file, my build section contains a custom task:

```
build {
   dependsOn customTask
}
```

However, this task seems to be called after vaadinCompile runs in the background.

Is there a way to make sure that my customTask runs before vaadinCompile?

**Comment by johndevs** [comment]
The build task depends on vaadinCompile so if you want to execute your custom task before vaadinCompile then you need to add the following:
```
vaadinCompile {
    dependsOn customTask
}
```
