### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by TSergey** [johndevs/gradle-vaadin-plugin#92]
Hi.
When I try to build vaadin application with the plugin I get the following error:
`Execution failed for task ':rms-ui:updateAddonStyles'.`
`> Cannot run program "java": CreateProcess error=206, The filename or extension is too long`

Debugging plugin I see that my classpath is really long and it's longer than allowed limit in windows (32 767 characters are allowed and I have about 33400).

Is there a chance this could be fixed?

**Comment by johndevs** [comment]
Closing this as ``vaadin.plugin.useClassPathJar = true`` should work.

**Comment by peterlitvak** [comment]
While using this option I get:
```
Cannot get property 'mainAttributes' on null object
```
any suggestions?

**Comment by kjordan2001** [comment]
Would it be possible to add this to the vaadinUpdateAddonStyles task?  I'm getting a "filename or extension is too long" there too.

**Comment by johndevs** [comment]
@kjordan2001 Yes, fixed this in #208. Should work with the next maintenance release (0.10.3).

**Comment by webb123** [comment]
Hi Javaru,
Use "Long path tool " will be helpful to solve your problem. Try it, gives good result

**Comment by Samantha258** [comment]
“Long Path Tool” is very helpful for this error !
You can use to solve this problem

**Comment by christoph-frick** [comment]
@Samantha258 do you plan to create new github user every week now to report back here? assuming, that you are an employee or do the "marketing" for that tool, it must be pretty pish, if that your attempt in selling it...

**Comment by aidencarter** [comment]
Long path tool is the very good program for error, unlock solution. 
Try it and solve your problem.
I used long path tool and I solve my error, unlock problem solution.

**Comment by christoph-frick** [comment]
Oh great, the marketing department is back from summer vacation.  What viral surprise strategy will it take this time?  The last one found it's early end by GH deleting that user...

**Comment by ahoehma** [comment]
Hello, we run into the same problem but with the maven plugin for vaadin :( https://vaadin.com/forum#!/thread/14201472

**Comment by aidencarter** [comment]
Long path tool is the very good program for error, unlock solution. 
Try it and solve your problem.
I used long path tool and I solve my error, unlock problem solution.

**Comment by wrightsanches1** [comment]
Long Path tool is a great tool for fixing problem.

**Comment by christoph-frick** [comment]
@wrightsanches1 reported you again.  Long Path pleeps are the worst...

**Comment by 1wrightsanches** [comment]
Long Path tool is a great tool for fixing problem.

**Comment by rivera15071976** [comment]
Please try long path tool

**Comment by frederik12345** [comment]
Hi I also experience this problem and only long path tool worked for me . Try using it . I hope it work. :)

**Comment by PeterCooks2** [comment]
LongPath Tool works best for me. Please try

**Comment by christoph-frick** [comment]
@PeterCooks2 reported
